import fs from 'node:fs/promises';
import path from 'node:path';

import type { BuildConfig } from '@earendil-works/gondolin';

export const agentVmRootfsInitExtraScript = `# Generated by agent-vm.
# Gondolin mounts devtmpfs over /dev at boot, so Docker-image /dev symlinks are hidden.
mkdir -p /dev
ln -sfn /proc/self/fd /dev/fd 2>/dev/null || true
ln -sfn /proc/self/fd/0 /dev/stdin 2>/dev/null || true
ln -sfn /proc/self/fd/1 /dev/stdout 2>/dev/null || true
ln -sfn /proc/self/fd/2 /dev/stderr 2>/dev/null || true
if [ ! -e /dev/ptmx ] && [ -e /dev/pts/ptmx ]; then
  ln -sfn pts/ptmx /dev/ptmx 2>/dev/null || true
fi
`;

interface PrepareRootfsInitExtraOptions {
	readonly buildConfig: BuildConfig;
	readonly configDir?: string;
	readonly imagePath: string;
}

function resolveBuildConfigPath(filePath: string, configDir: string | undefined): string {
	return path.isAbsolute(filePath) ? filePath : path.resolve(configDir ?? process.cwd(), filePath);
}

async function readExistingRootfsInitExtra(
	buildConfig: BuildConfig,
	configDir: string | undefined,
): Promise<string | undefined> {
	const existingRootfsInitExtra = buildConfig.init?.rootfsInitExtra;
	if (!existingRootfsInitExtra) {
		return undefined;
	}

	const resolvedRootfsInitExtra = resolveBuildConfigPath(existingRootfsInitExtra, configDir);
	try {
		return await fs.readFile(resolvedRootfsInitExtra, 'utf8');
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		throw new Error(
			`Failed to read Gondolin rootfs init extra '${resolvedRootfsInitExtra}': ${message}`,
			{ cause: error },
		);
	}
}

function composeRootfsInitExtra(existingRootfsInitExtra: string | undefined): string {
	return existingRootfsInitExtra
		? `${existingRootfsInitExtra.trimEnd()}\n\n${agentVmRootfsInitExtraScript}`
		: agentVmRootfsInitExtraScript;
}

export async function prepareBuildConfigWithAgentVmRootfsInitExtra(
	options: PrepareRootfsInitExtraOptions,
): Promise<BuildConfig> {
	const rootfsInitExtraPath = path.join(options.imagePath, 'agent-vm-rootfs-init-extra.sh');
	const existingRootfsInitExtra = await readExistingRootfsInitExtra(
		options.buildConfig,
		options.configDir,
	);

	await fs.writeFile(rootfsInitExtraPath, composeRootfsInitExtra(existingRootfsInitExtra), {
		encoding: 'utf8',
		mode: 0o755,
	});

	return {
		...options.buildConfig,
		init: {
			...options.buildConfig.init,
			rootfsInitExtra: rootfsInitExtraPath,
		},
	};
}
