export {
	oauthAuthorizationActionIdSchema as OAuthAuthorizationControllerActionIdSchema,
	oauthAuthorizationActionRequestSchema as OAuthAuthorizationControllerActionRequestSchema,
	oauthAuthorizationActionResultSchema as OAuthAuthorizationControllerActionResultSchema,
	type OAuthAuthorizationActionId as OAuthAuthorizationControllerActionId,
	type OAuthAuthorizationActionRequest as OAuthAuthorizationControllerActionRequest,
	type OAuthAuthorizationActionResult as OAuthAuthorizationControllerActionResult,
} from '@agent-vm/oauth-broker-contracts';
