import fs from 'node:fs/promises';
import path from 'node:path';

import type { BuildConfig } from '@earendil-works/gondolin';

export const agentVmRootfsInitExtraScript = `# Generated by agent-vm.
# Gondolin mounts devtmpfs over /dev at boot, so Docker-image /dev symlinks are hidden.
mkdir -p /dev
ln -sfn /proc/self/fd /dev/fd 2>/dev/null || true
ln -sfn /proc/self/fd/0 /dev/stdin 2>/dev/null || true
ln -sfn /proc/self/fd/1 /dev/stdout 2>/dev/null || true
ln -sfn /proc/self/fd/2 /dev/stderr 2>/dev/null || true
if [ ! -e /dev/ptmx ] && [ -e /dev/pts/ptmx ]; then
  ln -sfn pts/ptmx /dev/ptmx 2>/dev/null || true
fi
`;

interface PrepareRootfsInitExtraOptions {
	readonly buildConfig: BuildConfig;
	readonly imagePath: string;
	readonly rootfsInitExtraContent: string;
}

interface ResolveRootfsInitExtraOptions {
	readonly buildConfig: BuildConfig;
	readonly configDir?: string;
	readonly managedGatewayBoot?: GondolinManagedGatewayBootProjection;
}

/**
 * Backend projection of the domain-owned managed Gateway boot contract.
 *
 * The projection is deliberately closed: callers select the framework image
 * entry, while executable paths, arguments, environment-input paths, and log
 * identities remain adapter-owned image behavior.
 */
export interface GondolinManagedGatewayBootProjection {
	readonly frameworkBootEntry: 'hermes-framework-service' | 'openclaw-framework-service';
	readonly kind: 'managed-gateway-exact-two-role';
}

export interface ResolvedRootfsInitExtra {
	readonly content: string;
	readonly fingerprintInput: {
		readonly agentVmRootfsInitExtra: string;
		readonly deploymentRootfsInitExtra?: string;
		readonly managedGatewayBoot?: GondolinManagedGatewayBootProjection;
	};
}

const managedGatewayInputStagingRoot = '/run/agent-vm/managed-gateway-inputs';
const managedGatewayInputRoot = '/run/agent-vm/managed-gateway';
const managedGatewayRuntimeRoot = '/run/agent-vm/gateway-runtime';
const managedGatewayLogRoot = '/var/log/agent-vm';

function frameworkBootCommand(
	frameworkBootEntry: GondolinManagedGatewayBootProjection['frameworkBootEntry'],
): string {
	switch (frameworkBootEntry) {
		case 'hermes-framework-service':
			return '/usr/local/bin/agent-vm-hermes-gateway';
		case 'openclaw-framework-service':
			return '/usr/local/bin/openclaw gateway --port 18789';
	}
}

function frameworkLogFileName(
	frameworkBootEntry: GondolinManagedGatewayBootProjection['frameworkBootEntry'],
): string {
	return frameworkBootEntry === 'openclaw-framework-service'
		? 'openclaw-service.log'
		: 'hermes-service.log';
}

export function renderManagedGatewayRootfsInitScript(
	projection: GondolinManagedGatewayBootProjection,
): string {
	const selectedFrameworkBootCommand = frameworkBootCommand(projection.frameworkBootEntry);
	const selectedFrameworkLogPath = `${managedGatewayLogRoot}/${frameworkLogFileName(projection.frameworkBootEntry)}`;
	const frameworkBootInputFileNames =
		projection.frameworkBootEntry === 'hermes-framework-service'
			? 'framework.environment.sh framework-service.json config.yaml'
			: 'framework.environment.sh framework-service.json';
	return `# Fixed managed Gateway sibling boot entries.
managed_gateway_input_staging_root=${managedGatewayInputStagingRoot}
managed_gateway_input_root=${managedGatewayInputRoot}
mkdir -p ${managedGatewayLogRoot}
install -d -m 0700 "$managed_gateway_input_root"
install -d -m 0700 ${managedGatewayRuntimeRoot}
install -m 0600 /dev/null ${managedGatewayLogRoot}/tool-portal-service.log
install -m 0600 /dev/null ${selectedFrameworkLogPath}
(
  for managed_gateway_input_name in tool-portal.environment.sh tool-portal-service.json mcp.config.json; do
    if [ ! -f "$managed_gateway_input_staging_root/$managed_gateway_input_name" ]; then exit 78; fi
    install -m 0600 "$managed_gateway_input_staging_root/$managed_gateway_input_name" "$managed_gateway_input_root/$managed_gateway_input_name" || exit 78
  done
  exec /bin/sh -c 'set -a; . ${managedGatewayInputRoot}/tool-portal.environment.sh; set +a; exec /usr/local/bin/agent-vm-gateway-runtime --config ${managedGatewayInputRoot}/tool-portal-service.json'
) >> ${managedGatewayLogRoot}/tool-portal-service.log 2>&1 &
(
  for managed_gateway_input_name in ${frameworkBootInputFileNames}; do
    if [ ! -f "$managed_gateway_input_staging_root/$managed_gateway_input_name" ]; then exit 78; fi
    install -m 0600 "$managed_gateway_input_staging_root/$managed_gateway_input_name" "$managed_gateway_input_root/$managed_gateway_input_name" || exit 78
  done
  exec /bin/sh -c 'set -a; . ${managedGatewayInputRoot}/framework.environment.sh; set +a; exec ${selectedFrameworkBootCommand}'
) >> ${selectedFrameworkLogPath} 2>&1 &
`;
}

function resolveBuildConfigPath(filePath: string, configDir: string | undefined): string {
	return path.isAbsolute(filePath) ? filePath : path.resolve(configDir ?? process.cwd(), filePath);
}

async function readExistingRootfsInitExtra(
	buildConfig: BuildConfig,
	configDir: string | undefined,
): Promise<string | undefined> {
	const existingRootfsInitExtra = buildConfig.init?.rootfsInitExtra;
	if (!existingRootfsInitExtra) {
		return undefined;
	}

	const resolvedRootfsInitExtra = resolveBuildConfigPath(existingRootfsInitExtra, configDir);
	try {
		return await fs.readFile(resolvedRootfsInitExtra, 'utf8');
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		throw new Error(
			`Failed to read Gondolin rootfs init extra '${resolvedRootfsInitExtra}': ${message}`,
			{ cause: error },
		);
	}
}

function composeRootfsInitExtra(existingRootfsInitExtra: string | undefined): string {
	return existingRootfsInitExtra
		? `${agentVmRootfsInitExtraScript.trimEnd()}\n\n${existingRootfsInitExtra}`
		: agentVmRootfsInitExtraScript;
}

export async function resolveRootfsInitExtra(
	options: ResolveRootfsInitExtraOptions,
): Promise<ResolvedRootfsInitExtra> {
	if (options.managedGatewayBoot !== undefined && options.buildConfig.init?.rootfsInitExtra) {
		throw new Error(
			'Managed Gateway images cannot compose deployment-authored rootfs init authority.',
		);
	}
	const existingRootfsInitExtra = await readExistingRootfsInitExtra(
		options.buildConfig,
		options.configDir,
	);
	const managedGatewayRootfsInitExtra =
		options.managedGatewayBoot === undefined
			? undefined
			: renderManagedGatewayRootfsInitScript(options.managedGatewayBoot);
	const composedRootfsInitExtra = composeRootfsInitExtra(existingRootfsInitExtra);

	return {
		content:
			managedGatewayRootfsInitExtra === undefined
				? composedRootfsInitExtra
				: `${composedRootfsInitExtra.trimEnd()}\n\n${managedGatewayRootfsInitExtra}`,
		fingerprintInput: {
			agentVmRootfsInitExtra: agentVmRootfsInitExtraScript,
			...(existingRootfsInitExtra === undefined
				? {}
				: { deploymentRootfsInitExtra: existingRootfsInitExtra }),
			...(options.managedGatewayBoot === undefined
				? {}
				: { managedGatewayBoot: options.managedGatewayBoot }),
		},
	};
}

export async function prepareBuildConfigWithAgentVmRootfsInitExtra(
	options: PrepareRootfsInitExtraOptions,
): Promise<BuildConfig> {
	const rootfsInitExtraPath = path.join(options.imagePath, 'agent-vm-rootfs-init-extra.sh');

	await fs.writeFile(rootfsInitExtraPath, options.rootfsInitExtraContent, {
		encoding: 'utf8',
		mode: 0o755,
	});

	return {
		...options.buildConfig,
		init: {
			...options.buildConfig.init,
			rootfsInitExtra: rootfsInitExtraPath,
		},
	};
}
