import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import { updateAgentVmManual } from './manual-commands.js';

const createdDirectories: string[] = [];

afterEach(async () => {
	const directories = createdDirectories.splice(0);
	await Promise.all(
		directories.map((directoryPath) => fs.rm(directoryPath, { force: true, recursive: true })),
	);
});

async function createTestDirectory(): Promise<string> {
	const testDirectory = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-vm-manual-'));
	createdDirectories.push(testDirectory);
	return testDirectory;
}

async function readText(targetDir: string, relativePath: string): Promise<string> {
	return await fs.readFile(path.join(targetDir, relativePath), 'utf8');
}

describe('updateAgentVmManual', () => {
	it('writes generated manual files plus AGENTS.md and CLAUDE.md symlink', async () => {
		const targetDir = await createTestDirectory();

		const result = await updateAgentVmManual({
			defaultZoneId: 'shravan',
			systemConfigPath: 'config/system.json',
			targetDir,
			updateAgentIndex: true,
		});

		expect(result.updated).toContain('docs/manual/README.md');
		expect(result.updated).toContain('AGENTS.md');
		expect(await readText(targetDir, 'docs/manual/README.md')).toContain(
			'Generated by agent-vm manual',
		);
		expect(await readText(targetDir, 'AGENTS.md')).toContain('docs/manual/README.md');
		expect(await fs.readlink(path.join(targetDir, 'CLAUDE.md'))).toBe('AGENTS.md');
	});

	it('preserves user-owned local manual notes when updating generated files', async () => {
		const targetDir = await createTestDirectory();
		await fs.mkdir(path.join(targetDir, 'docs', 'manual'), { recursive: true });
		await fs.writeFile(
			path.join(targetDir, 'docs', 'manual', 'local-notes.md'),
			'deployment-owned notes\n',
			'utf8',
		);

		await updateAgentVmManual({
			defaultZoneId: 'shravan',
			systemConfigPath: 'config/system.json',
			targetDir,
			updateAgentIndex: true,
		});

		expect(await readText(targetDir, 'docs/manual/local-notes.md')).toBe(
			'deployment-owned notes\n',
		);
	});

	it('does not update AGENTS.md unless updateAgentIndex is true', async () => {
		const targetDir = await createTestDirectory();
		await fs.writeFile(path.join(targetDir, 'AGENTS.md'), 'custom agent index\n', 'utf8');

		const result = await updateAgentVmManual({
			defaultZoneId: 'shravan',
			systemConfigPath: 'config/system.json',
			targetDir,
			updateAgentIndex: false,
		});

		expect(result.updated).not.toContain('AGENTS.md');
		expect(await readText(targetDir, 'AGENTS.md')).toBe('custom agent index\n');
	});
});
