export const GENERATED_MANUAL_MARKER = 'Generated by agent-vm manual. Do not edit by hand.';

export interface ManualTemplateOptions {
	readonly defaultZoneId: string;
	readonly systemConfigPath: string;
}

export interface ManualTemplateFile {
	readonly content: string;
	readonly relativePath: string;
}

function generatedPage(title: string, body: string): string {
	return `<!-- ${GENERATED_MANUAL_MARKER} -->

# ${title}

${body.trim()}
`;
}

export function buildAgentVmAgentsTemplate(options: ManualTemplateOptions): string {
	return generatedPage(
		'Agent Instructions',
		`
This deployment uses agent-vm. Start with docs/manual/README.md, then drill into the specific manual page for the task.

Primary config:
- System config: ${options.systemConfigPath}
- Default zone: ${options.defaultZoneId}

Use docs/manual/layout.md before moving files or changing generated folders.
Use docs/manual/image-versioning.md before changing agent-vm package pins, managed image pins, OpenClaw runtime package pins, or generated Dockerfiles.
Use docs/manual/tool-vm-leases.md before changing agent-vm Tool VM lease identity, renewal, or reuse behavior.
Use docs/manual/gateway-ingress.md before changing gateway ports, OpenClaw Control UI access, SSE/streaming behavior, WebSocket access, or serving additional webservers from inside a VM.
Use docs/manual/operations.md before debugging agent-vm controller health, gateway service health, lease-heartbeat, lease-renew, Tool VM SSH, or Gondolin tcpHosts timeouts.
Use docs/manual/observability.md before changing host observability, Victoria storage, OpenTelemetry collector ports, OpenClaw diagnostics flags, or logging behavior.
Use docs/manual/mcp-portal.md before changing MCP providers, managed Tool Portal profiles, standalone MCP Portal profiles, MCP package pins, or live MCP validation.
Use docs/manual/tool-access.md before answering whether a tool binary, auth profile, or tool VM image should be agent-specific.
Use docs/manual/channels.md before helping a human configure Discord, Slack, Telegram, or another OpenClaw channel.
Use docs/manual/runtime-paths.md before answering where files appear inside VMs or how managed Tool VMs separate durable /workspace, disposable /work, and optional /gitdirs.
Use docs/manual/per-agent-setup.md before changing multi-agent layouts, OpenClaw scope=agent configuration, or per-agent tool/auth isolation.

Do not assume Discord is enabled by the framework. Channels and channel secrets are deployment-owned.
Do not silently edit privileged host/deployment config. Explain the proposed Dockerfile, secret, egressHosts, websocketUpgrades, or OpenClaw config change and wait for the human to ask you to apply it.
`,
	);
}

export function buildManualTemplateFiles(
	options: ManualTemplateOptions,
): readonly ManualTemplateFile[] {
	return [
		{
			relativePath: 'docs/manual/README.md',
			content: generatedPage(
				'agent-vm Deployment Manual',
				`
This manual is generated from the installed agent-vm package. It is the deployment-local guide for coding agents helping end users set up and operate agent-vm deployments.

Read in this order:
1. layout.md explains generated folders and ownership.
2. image-versioning.md explains package pins, managed image pins, overlays, and generated Dockerfiles.
3. tool-vm-leases.md explains agent-keyed Tool VM lease identity and reuse.
4. openclaw.md explains OpenClaw gateway configuration.
5. gateway-ingress.md explains host-facing gateway ports, OpenClaw web serving, SSE, WebSockets, and the boundary between single-route OpenClaw ingress and additional guest webservers.
6. openclaw-defaults.md explains agent-vm-owned OpenClaw defaults and doctor checks.
7. observability.md explains managed or external host observability setup, build-time Docker Compose startup for managed stacks, controller startup behavior, and telemetry safety rules.
8. mcp-portal.md explains managed Tool Portal policy, standalone MCP Portal policy, progressive MCP discovery, and gateway-owned MCP auth.
9. tool-access.md explains binary, auth, OpenClaw tool, and zone/image isolation.
10. channels.md explains how deployments add Discord or other channels.
11. runtime-paths.md explains /workspace, /work, optional /gitdirs, and other in-VM paths.
12. per-agent-setup.md explains multi-agent layout and tool access choices.
13. migration-discord.md explains how existing Discord deployments keep working.
14. secrets.md explains runtime auth and HTTP mediation.
15. operations.md explains start, graceful stop, scoped offline cleanup, health snapshots, lease-heartbeat, lease-renew, gateway-service health, and gateway-to-controller control-session checks.

Local deployment notes belong in docs/manual/local-notes.md or another non-generated file.
`,
			),
		},
		{
			relativePath: 'docs/manual/layout.md',
			content: generatedPage(
				'Generated Layout',
				`
${options.systemConfigPath} is the controller config. Agent-vm-authored config is JSONC so short local comments are allowed.
config/gateways/<zone>/openclaw.json is OpenClaw-owned gateway config.
config/gateways/<zone>/worker.jsonc is Agent Worker gateway config when the zone type is worker.
vm-images/ contains deployment-owned Gondolin build-config.jsonc files and small managed image overlays.
agent-vm owns the gateway/tool base image recipes and pins the managed GHCR base layer version.
storageRootDir is the required, final deployment storage root. Generated local, user-dir, and pod scaffolds scope it by host.projectNamespace. The controller loads that full path and derives cacheDir, controllerStateDir, controllerRuntimeDir, and each zone's stateDir, optional zoneFilesDir, and zoneRuntimeDir without appending the namespace again.
stateDir is <storageRootDir>/<zoneId>/state and stores durable gateway state.
zoneFilesDir stores durable shared zone files and per-agent workspaces for managed Gateway zones. It is derived at <storageRootDir>/<zoneId>/zone-files. Each configured agent owns zoneFilesDir/agents/<agentId>. Worker zones have no active zoneFilesDir.
gateway.backupIdentity selects the host-resolved Age identity required by backup create and restore. Backup list does not resolve it, and there is no implicit identity fallback.
cacheDir is <storageRootDir>/cache and stores rebuildable artifacts.
controllerStateDir is required as a derived controller capability at <storageRootDir>/controller-state and stores host-controller-only durable authority.
controllerStateDir is never mounted into a Gateway or Tool VM and must remain disjoint from config, cache, runtime, Gateway state, backup, observability, and mount-source paths.
All controller records live below the one host-controller-owned root at controllerStateDir/zones/<zoneId>: approvals/, gateway-runtime.json, tool-leases/<recordId>.json, and worker-tasks/<taskId>/gateway-runtime.json.
controllerRuntimeDir is <storageRootDir>/controller-runtime and stores the controller ownership lock, health evidence, and generated observability files.
zoneRuntimeDir is <storageRootDir>/<zoneId>/runtime and stores zone logs, workspace Git databases, Worker task runtime, and control-session material outside normal backup.
When zones[].agents[].workspaceGit is enabled, its isolated Git database lives at zoneRuntimeDir/gitdirs/agents/<agentId>/workspace.git while the durable workspace remains under zoneFilesDir/agents/<agentId>.

Author JSONC for human-owned agent-vm config. Runtime files such as /state/effective-worker.json, task event JSONL, runtime records, and API bodies stay strict JSON.
OpenClaw gateway VMs mount zoneFilesDir at /zone.
Managed OpenClaw Tool VMs expose only the selected agent's filtered durable workspace at /workspace. They do not mount the whole /zone tree.
Managed Tool VMs use rootfs/COW /work for disposable execution and optionally expose only the selected workspace Git database at /gitdirs/workspace.git. No generic /agent-vm surface is mounted unless a future contract names its exact generated inventory and owner.
Worker task VMs keep repo files on rootfs/COW at /work/repos.
OpenClaw gateway VMs use /work/tmp and /work/cache for disposable runtime work.
`,
			),
		},
		{
			relativePath: 'docs/manual/image-versioning.md',
			content: generatedPage(
				'Image Versioning',
				`
There is one owner for each version decision.

package.json owns which installed @agent-vm/* package version this deployment uses. Upgrade agent-vm by changing package.json and the lockfile, then run agent-vm manual update and agent-vm build from that installed package.

controller start refuses a stale prepared Gateway image when its fingerprint does not match the currently installed agent-vm runtime and build inputs. Startup does not rebuild images automatically; run agent-vm build from the installed package, then retry controller start.

The installed @agent-vm/agent-vm package owns managed-images.json. That manifest selects the managed GHCR base image tags and managed OpenClaw default version tested with that package. Deployment repos should not copy or edit managed-images.json.

vm-images/.../overlay.jsonc owns deployment image additions. Use extraAptPackages for apt packages, copy for deployment files, runAfterBase for post-base commands, and packageOverrides only for deliberate image-local package pins such as a temporary @openclaw/discord rollback or an explicit undici floor. Do not restate the managed default package set in deployment overlays.

Managed package defaults belong under baseImages.<base>.packageOverrides in the installed agent-vm package's managed-images.json. For example, an agent-vm-managed OpenClaw 2026.6.8 image may print overrides undici@8.5.0[managed-images.json/packageOverrides.pnpm] while the upstream OpenClaw package line still carries the older transitive dependency. Remove that managed default only after fresh package evidence shows OpenClaw and required @openclaw/* packages no longer resolve the vulnerable dependency.

Do not edit cacheDir/generated-dockerfiles/... by hand. Generated Dockerfiles are build output. If a generated Dockerfile contains the wrong package version, change package.json or the overlay that produced it, then rebuild.

For OpenClaw gateway images, agent-vm build resolves packages in this order:
1. @agent-vm/openclaw-agent-vm-plugin comes from the installed agent-vm package.
2. managed default OpenClaw, npm, and pnpm package overrides come from managed-images.json baseImages.<base>.packageOverrides.
3. overlay packageOverrides override managed defaults by package name inside the selected image profile only.
4. packageOverrides.pnpm applies exact transitive package workarounds and relinks matching bundled OpenClaw package copies.
5. generated Dockerfiles receive the resolved package specs only as disposable output.

If the deployment installs openclaw in package.json for host-side validation, keep it aligned with the runtime version chosen by the overlay. Treat package.json's openclaw entry as the validation tool mirror, not the runtime image owner.

agent-vm build prints the resolved base image, generated Dockerfile path, OpenClaw plugin package, OpenClaw runtime packages, and the source of each version before Docker and Gondolin work begin. Read that plan before debugging Docker output.
`,
			),
		},
		{
			relativePath: 'docs/manual/tool-vm-leases.md',
			content: generatedPage(
				'Tool VM Lease Identity And Reuse',
				`
Managed OpenClaw and Hermes Tool VMs are agent-keyed: one compatible Tool VM per zone and Agent VM agent id.
The framework integration authenticates the native OpenClaw agent or Hermes profile, selects its controller-authored projection, and sends typed requests to the common Tool Portal service over the private UDS. Framework scope/session metadata does not choose, identify, renew, list, log, or store Tool VM leases.
The controller resolves the stable agent identity to controller-owned workspace, optional workspace Git, and Tool VM profile capabilities. Caller-supplied Gateway or host paths do not select storage. The lease identity remains zoneId + agentId, not a path string.
TCP slots are capacity; they are not identity.
The common Tool Portal service owns current-epoch agent bindings, per-agent strict SSH connections, Sandbox operations, and active-use tracking. It renews reusable bindings and heartbeats active shell/file/process operations over its private controller relationship so long commands are not reaped mid-run.
Health snapshots include lease-renew and lease-heartbeat observations. Both keep lease state alive when successful, but they prove different things: lease-renew proves an idle cached lease can be reused, while lease-heartbeat proves an active operation still has a live private control-session path.

If the Tool Portal service observes stale Tool VM SSH evidence, it retires the old binding before the next operation and asks the controller for current replacement access. The controller re-checks old-binding authority, current caller context, session fence, workspace, profile, and agent ownership before publishing new service-private SSH material.
The old lease id is correlation only, not authority. No later shell, file, exec, heartbeat, or finalize work may use the old lease id or old SSH identity after stale evidence. Framework integrations never receive lease ids or SSH material.

Example:
- shravan agent uses agentId=shravan.
- alevtina agent uses agentId=alevtina.
- Each agent gets its own compatible Tool VM lease with its filtered durable workspace at /workspace and disposable rootfs/COW work at /work.
- Managed OpenClaw and Hermes support multiple declared agents in the same zone when their per-agent config is explicit and consistent.
- defaultToolVmProfile is the fallback Tool VM image; agentToolVmProfiles can select a different image per declared agent.
- Use separate zones when gateway lifecycle or channel isolation matters more than sharing a gateway VM.
- Configure gateway.authProfilesByAgent only when agents intentionally need separate prebuilt OpenClaw auth profiles. Agent-authored durable files live in that agent's zoneFilesDir/agents/<agentId> workspace.
- Use separate zones when gateway lifecycle isolation or shared-zone cost is worse than another gateway VM.
`,
			),
		},
		{
			relativePath: 'docs/manual/operations.md',
			content: generatedPage(
				'Operations',
				`
Use graceful controller stop first:

agent-vm controller stop --config ${options.systemConfigPath}

If the controller HTTP server is broken or gone, use scoped offline cleanup:

agent-vm controller cleanup --config ${options.systemConfigPath} --zone ${options.defaultZoneId}

Offline cleanup first acquires the same deployment-wide ownership lock held by a running controller, then refuses to run while the configured controller health endpoint is reachable. --force skips only that advisory health probe; it never bypasses the ownership lock or exact-evidence checks.

The ownership lock provides mutual exclusion; it is not destruction evidence. Cleanup validates schema-v2 records under controllerStateDir/zones/<zoneId>: Tool records at controllerStateDir/zones/<zoneId>/tool-leases/<recordId>.json first, then controllerStateDir/zones/<zoneId>/gateway-runtime.json. Records bind canonical config path, controller port, project namespace, zone, full Gateway parent identity, VM id, pid, and process command/start identity as applicable. The controller revalidates the live process and endpoint, never adopts an old VM, and deletes a record only after exact process and endpoint absence is proven.

Old, malformed, mismatched, occupied-endpoint, or otherwise unproven records fail closed and remain for diagnosis. Unknown identity preserves the evidence and prevents Gateway replacement or Tool TCP-slot reuse. Gateway subtree cleanup runs at most four child destroys concurrently, and the whole subtree has a 300 second deadline. An incomplete disposition leaves the old Gateway owner-unsafe and refuses a replacement until cleanup is proven complete.

Do not use broad QEMU process kills as normal deployment workflow. Multiple agent-vm installations can run on one host, and broad process matching can kill the wrong installation.

Local package scripts should be thin wrappers around these commands. Deployment repos should not copy process-fencing logic.

Health model:
- GET /health is the global agent-vm controller liveness endpoint.
- GET /zones/<zoneId>/health is an on-demand live readiness probe.
- GET /zones/<zoneId>/service-health is an on-demand live gateway-service liveness probe.
- GET /zones/<zoneId>/health-snapshot is an in-memory zone health view.
- agent-vm controller health --config <system-config> --zone <zoneId> prints the live readiness probe result.
- agent-vm controller service-health --config <system-config> --zone <zoneId> prints the live gateway-service liveness probe result.
- agent-vm controller health-snapshot --config <system-config> --zone <zoneId> prints the in-memory zone health snapshot.
- Health snapshots separate gateway infrastructure, gateway service, channel-provider, and Tool VM lease health.
- gateway-service-health means the agent-vm controller can probe gateway service liveness through the gateway VM runtime. For OpenClaw, periodic monitoring and explicit service-health use /health; explicit zone health probes /readyz.
- gateway-control-session means the agent-vm controller owns a private Socket.IO control session into the gateway VM through Gondolin ingress.
- agent-channel-provider-health means the gateway/plugin reports whether an agent channel provider can communicate. The controller reads only generic health values such as healthy, transitioning, unhealthy-recoverable, and unhealthy-unrecoverable.
- gateway-recovery means the controller attempted an automatic whole-Gateway VM restart or cold start after Gateway service, control-session, or sibling-lifecycle evidence required replacement.
- gateway-recovery-suspended means repeated automatic restarts failed and the controller paused further auto-recovery for that zone until the reset window expires.
- lease-heartbeat means an active Tool VM operation can refresh its active use.
- lease-renew means an idle cached Tool VM lease can be reused.
- tool-vm-ssh means command, file-bridge, finalize, or probe SSH operations on the gateway-to-Tool-VM path.
- tool-vm-ssh lifecycle events distinguish Tool Portal service observations from controller_final decisions. A controller_final stale_to_reacquired event proves the controller accepted one replacement transition for the old lease and records old/replacement lease correlation using redacted public ids.

Health snapshots and bounded event history are in-memory controller state for live diagnosis. Accepted health and recovery events are also appended to <controllerRuntimeDir>/controller-health/events.jsonl as diagnostic evidence; that log and exported telemetry are not lifecycle authority. The controller owns lifecycle decisions; schema-v2 runtime records plus revalidated process and endpoint identity are durable crash-cleanup evidence.

By default, controller.health.gatewayServiceAutoRestart observes gateway-service and gateway-control-session degradation. The managed Tool Portal and selected framework processes are VM-boot siblings; neither supervises or restarts the other. Unrecoverable sibling or control-session failure retires the Gateway epoch and uses whole-Gateway VM recovery. The same recovery path can cold-start a failed or stopped Gateway when current ownership checks prove it is safe. Gateway recovery has a 61 minute cooldown per zone and a 10 minute restart deadline. Gateway replacement releases active Tool VM leases for that zone first, so in-flight tool work is interrupted instead of keeping stale SSH state alive. After 3 consecutive failed automatic Gateway recoveries, the controller records gateway-recovery-suspended and pauses further auto-recovery for that zone until the 24 hour reset window expires.

Channel-provider failures are diagnostic input only through the generic contract by default. A channel provider marked unhealthy-recoverable degrades readiness/status but does not restart the gateway unless controller health policy explicitly enables restartGatewayOnRecoverable. A channel provider marked unhealthy-unrecoverable is surfaced for operator diagnosis and does not restart the gateway by default. Provider-specific details stay in the event payload; the controller must not branch on Discord, Slack, or other platform-specific names.

secret-resolution-failed is a recovery blocker, not proof of the original outage cause. Show it as the reason a start, restart, credentials refresh, or cold-start cannot proceed now unless durable lifecycle evidence proves the outage began during that operation.

Use agent-vm controller credentials check --zone <zone> to verify gateway secret resolution without contacting the controller or restarting the gateway. Use credentials refresh only when the operator intentionally wants a credential refresh and zone runtime restart.

Tool VM lease failures retire or quarantine one lease before gateway restart. A tool-vm-ssh failure should not be treated as gateway infrastructure failure unless lease-manager or gateway control-session health also proves a broader gateway problem.

Health timeouts are operation-specific. Short health probes should fail quickly; git push/pull and lease-create get longer budgets. Do not assume every abort means the work should be killed.
`,
			),
		},
		{
			relativePath: 'docs/manual/openclaw.md',
			content: generatedPage(
				'OpenClaw Gateway',
				`
Agent-vm provides VM lifecycle, storage mounts, TCP/HTTP mediation, image build, and tool VM leases.
OpenClaw owns plugin lifecycle, agents.list, channels, and gateway behavior.
Managed Gateway boot starts one common Tool Portal service process beside OpenClaw. The thin OpenClaw plugin authenticates the native agent and sends Tool Portal Capability API and SSH Sandbox API requests through one GatewayRuntimeClient over the private UDS.
The controller remains durable lease authority. ToolPortalService owns current-epoch bindings, per-agent strict SSH connections, active uses, and Sandbox operations. OpenClaw receives API results, not lease ids or SSH material. Command stdout, stderr, and file traffic flow through the private UDS and the service-owned gateway-to-Tool-VM SSH data path.
OpenClaw application heartbeat turns are not infrastructure health checks. Use agent-vm health snapshots to distinguish gateway-service health, gateway-to-controller control session, lease-heartbeat, lease-renew, and Tool VM SSH health.
Channel-provider details stay inside OpenClaw/plugin payloads. The controller branches only on generic channel-provider health: healthy, transitioning, unhealthy-recoverable, and unhealthy-unrecoverable. Recoverable channel-provider failures degrade readiness/status by default; gateway VM restart is opt-in through controller health policy.

The default scaffold enables Gondolin and memory-core support. It does not enable Discord.
OpenClaw-owned openclaw.json stays strict JSON unless OpenClaw itself supports comments or agent-vm renders a strict effective config first.

Multi-zone controller work makes one controller process manage multiple typed zones. Use defaultToolVmProfile, agentToolVmProfiles, gateway.authProfilesByAgent, zones[].agents[].workspaceGit, leaseIdleTtl, and tcpPool from the current system config reference for exact field names.
`,
			),
		},
		{
			relativePath: 'docs/manual/observability.md',
			content: generatedPage(
				'Host Observability',
				`
Host observability is deployment-configured. Enable host.observability in ${options.systemConfigPath}. Per-zone observability supports managed OpenClaw and Hermes gateways through Gondolin HTTP mediation. Each enabled zone configures separate framework and common Tool Portal signal policies under zones[].observability.services. The old collector route depended on raw Gondolin tcpHosts and must not be restored.

Use host.observability.stack.mode=managed when this deployment should own the local Victoria + OpenTelemetry Collector stack. In managed mode, host.observability.stack.scrubbing.responsibility defaults to agent-vm-managed-collector. Agent-vm build prepares the host stack when host.observability.prepareOnBuild is true and at least one selected managed OpenClaw or Hermes zone has zones[].observability enabled. The build step renders docker-compose.observability.yml and otel-collector-config.yaml under controllerRuntimeDir/observability/<projectNamespace>, creates durable Victoria data directories under host.observability.dataDir, then runs docker compose up -d. Generated Compose services use restart: unless-stopped so Docker can restore them after daemon or host recovery. Use agent-vm build --no-observability to skip the host stack for one build run.

Use host.observability.stack.mode=external when a shared collector is already managed outside this deployment. External mode never renders or starts Docker Compose and does not require host.observability.dataDir or retention. Set host.observability.stack.scrubbing.responsibility=external-collector to make the external collector sanitization responsibility explicit, and keep that collector available on the configured loopback collector ports.

Controller startup does not start Docker Compose. With controllerStartPolicy=degraded, the controller binds and starts while it checks host observability readiness in the background. Managed mode checks the OpenTelemetry collector plus Victoria metrics, logs, and traces endpoints. External mode checks only the configured OpenTelemetry collector health endpoint. With controllerStartPolicy=require-ready, startup waits only for the configured total bounded readiness budget and fails if the configured collector or already-prepared managed stack is unavailable. With controllerStartPolicy=off, startup does not check host observability.

For managed mode, keep durable host.observability.dataDir outside storageRootDir. Victoria data is intentionally independent from rebuildable cache and disposable controller or zone runtime folders. Retention is configured separately for metrics, logs, and traces with period plus optional disk bounds.

Published ports bind to loopback only. Do not publish collector or Victoria ports on broad host interfaces unless a separate, authenticated access layer owns that exposure.

Enable zones[].observability only for managed OpenClaw or Hermes zones that should export framework and Tool Portal diagnostics to the host collector. Worker zones reject it. The gateway sends OTLP to a synthetic collector host that agent-vm rewrites to the configured loopback collector. Tool VM SSH is the only managed gateway raw TCP exception.

Service identities are fixed: agent-vm-openclaw, agent-vm-hermes, and agent-vm-tool-portal. Do not author serviceName. Each producer suppresses content and baggage and uses its own fixed bounded lossy queue; collector scrubbing remains defense in depth. Only OpenClaw zones may use the optional zones[].observability.openclaw.diagnosticsFlags extension.

Do not inject OPENCLAW_DIAGNOSTICS through rawEnvSecrets to recreate the old collector route. Authored OpenClaw logging.redactSensitive must stay enabled.

Never log secrets, prompts, message bodies, tool payloads, cookies, authorization headers, token values, raw URLs with query strings, private keys, or command content. The managed OpenTelemetry collector drops known sensitive attributes before export and Victoria Logs ignores known sensitive fields, but that is defense-in-depth. External collectors must provide equivalent sanitization before storing or forwarding agent-vm telemetry. Source logging still owns the first safety boundary.
`,
			),
		},
		{
			relativePath: 'docs/manual/gateway-ingress.md',
			content: generatedPage(
				'Gateway Ingress And Serving',
				`
Agent-vm exposes OpenClaw gateway HTTP through Gondolin ingress. Keep three layers separate:

1. zones[].gateway.port is the host-facing Gondolin ingress listener.
2. Gondolin routes request path prefixes to guest loopback HTTP ports.
3. OpenClaw serves its Control UI, gateway WebSocket, /healthz, /readyz, /v1/chat/completions, /v1/responses, and plugin HTTP routes from its guest gateway port.

The current OpenClaw gateway route is intentionally simple: agent-vm sets one route, "/" -> the OpenClaw guest gateway port. That one route is enough for the OpenClaw Control UI, OpenAI-compatible APIs, SSE streaming, readiness probes, and WebSocket traffic when OpenClaw is the only guest web server being exposed.
For /v1/chat/completions, the request model selects the OpenClaw agent, not the underlying provider model. Use "openclaw" or "openclaw/<agentId>" in the HTTP request body; configure provider models inside the OpenClaw agent defaults.

SSE and streaming responses need incremental forwarding. Agent-vm keeps Gondolin response buffering disabled for gateway ingress. If a request waits a long time before the first byte, tune zones[].gateway.ingress.upstreamHeaderTimeoutMs. If a long response can sit idle between body chunks, tune zones[].gateway.ingress.upstreamResponseTimeoutMs. Streaming responses are less sensitive to the body idle timeout when the model emits regular chunks.

Do not treat gateway.ingress timeout settings as a general "open ports" mechanism. Serving additional guest HTTP services, such as a Vite preview, local app server, or sidecar dashboard, requires explicit additional Gondolin ingress routes that map non-root path prefixes to guest ports. Route prefixes should be designed so they do not shadow OpenClaw's "/" route, API routes, Control UI assets, or WebSocket endpoint.

Raw TCP services are not HTTP ingress. Use configured tcpHosts for VM-to-host raw TCP mappings and keep HTTP serving on Gondolin ingress routes.
	`,
			),
		},
		{
			relativePath: 'docs/manual/openclaw-defaults.md',
			content: generatedPage(
				'OpenClaw Defaults',
				`
Agent-vm scaffolds OpenClaw defaults that make the deployment usable without hand-editing Dockerfiles or OpenClaw internals.

	agents.defaults.sandbox.backend is gondolin, mode is all, and scope is agent. Agent-vm rejects OpenClaw Tool VM leases that are not agent-scoped.
	agents.defaults.sandbox.workspaceAccess is rw so agents can write their workspace.
	agents.defaults.workspace points at /zone/agents/default so /zone remains shared zone storage.
	agents.defaults.model.primary is openai/gpt-5.5.
	agents.defaults.models["openai/gpt-5.5"].agentRuntime.id is pi so GPT-5.5 runs through the PI harness.
	session.dmScope is per-channel-peer so Discord DMs from different people do not share one agent session.
		approvals.plugin.enabled is true with approvals.plugin.mode=session for OpenClaw-owned plugin approval prompts. Managed Tool Portal calls.requiresApproval uses the controller-owned approval surface and requires zone approvalAccess when any tool is effectively admitted; calls.withoutApproval remains the direct-call policy. Exec approval forwarding remains deployment-owned.
		tools.web.fetch.ssrfPolicy trusts fake-IP ranges for web_fetch. For gateway/tool TCP mappings, agent-vm's Gondolin adapter uses RFC2544 synthetic IPv4 plus ::ffff:198.18.0.1 as the synthetic AAAA answer so OpenClaw SSRF checks can validate all DNS answers without a broad hostname bypass.
		tools.sandbox.tools.alsoAllow includes web_search, web_fetch, message, and group:plugins so sandboxed sessions can see web tools once a provider is configured, can explicitly send channel replies when OpenClaw uses message_tool_only group reply delivery, and can see optional plugin-owned tools such as tool_portal_*.
	plugins.load.paths includes /home/openclaw/.openclaw/extensions for agent-vm-managed extensions and the package manager's global root for managed OpenClaw packages.
	plugins.slots.memory selects memory-core when memory-core is enabled.
	gateway.auth.mode is token for agent-vm-managed gateways.
	logging.file is rendered in the effective OpenClaw config as /agent-vm/logs/openclaw-YYYY-MM-DD.log unless the deployment explicitly sets its own logging.file.

		Managed OpenClaw gateway images install @agent-vm/openclaw-agent-vm-plugin and register it as the gondolin extension. The gondolin extension is a thin client: it registers Tool Portal native tools and forwards Capability API and SSH Sandbox API requests to the common Tool Portal service over the private UDS.
		Managed OpenClaw gateway images install external channel packages required by config. For example, channels.discord.enabled asks for @openclaw/discord. The managed release supplies the default version unless vm-images/gateways/openclaw/overlay.jsonc pins that package in packageOverrides.openclaw. Transitive workarounds use packageOverrides.pnpm, and the rebuilt image must be inspected before calling that workaround active.

	Use agent-vm init --openclaw-agents sun,shravan to scaffold declared same-zone managed OpenClaw agents with /zone/agents/<id> workspaces. Keep OpenClaw agents.list, zones[].agents, Tool Portal agent assignments, and the MCP provider catalog aligned before validation. For OpenClaw provider auth, gateway.authLogin.defaultAgent may own the shared profile store; use gateway.authProfilesByAgent only when agents intentionally need separate prebuilt auth profile files.

	Run agent-vm validate after editing OpenClaw config or system config. Validate owns static schema and policy shape, including removed fields and WebSocket upgrade policy. Run agent-vm doctor after rebuilding or starting the deployment to check runtime host readiness, plugin paths, memory slots, workspace access, sandbox plugin tools, and configured auth profile material.
	`,
			),
		},
		{
			relativePath: 'docs/manual/mcp-portal.md',
			content: generatedPage(
				'MCP Portal',
				`
Managed Gateway Tool Portal, standalone Tool Portal, and standalone MCP Portal are separate operating surfaces. Managed OpenClaw exposes Tool Portal native tools in the Gateway VM. External consumers may use explicitly configured standalone Tool Portal entrypoints or the separate mcp-portal mcp-proxy serve command.

Managed Gateway boot starts one common Tool Portal service process beside the selected OpenClaw or Hermes framework process. Each thin framework integration authenticates its native agent/profile and uses one GatewayRuntimeClient over the private UDS. ToolPortalService owns policy, controller bindings, per-agent strict SSH, active uses, and Sandbox operations; the integrations never receive lease ids or SSH material.

Tool Portal is the model-visible cross-backend contract layer for managed OpenClaw and Hermes. It composes MCP providers, controller host actions, and Tool VM runners behind one capability vocabulary. Its managed config pair is mcp.config.jsonc plus tool-portal.config.jsonc. Standalone Tool Portal uses tool-portal.config.jsonc with mode standalone and explicitly configured HTTP/MCP/stdio entrypoints. Standalone MCP Portal is a separate product that loads mcp.config.jsonc plus mcp-portal.config.jsonc. Managed Gateway does not load mcp-portal.config.jsonc or use standalone bearer/HMAC policy as managed authority, and it exposes no Tool Portal HTTP/MCP/stdio listener or public ingress.

		Agents should use progressive disclosure:
		1. tool_portal_list with requests[] for allowed capabilities and compact summaries.
		2. tool_portal_search with requests[] for discovery inside the scoped index.
		3. tool_portal_describe with requests[] for full JSON Schema and optional TypeScript/Zod helpers.
		4. tool_portal_call with calls[] to call authorized capabilities by namespace + name after seeing the schema.

	The Capability API above is distinct from the managed-only SSH Sandbox API. Capability calls select namespace + name and apply catalog, call, approval, and backend policy. OpenClaw SandboxBackend and Hermes BaseEnvironment use GatewayRuntimeClient.sandbox for direct authenticated environment, shell, filesystem, process, stream, and terminal operations. Both paths may use the same current agent binding and service-owned SSH connection only after their distinct admission.

	All portal responses are { ok, items, diagnostics? }. Each item has id and status. Successful items use { status: "ok", value }; failed items use { status: "error", error }.

		For Managed Gateway, mcp.config.jsonc owns upstream MCP providers and tool-portal.config.jsonc owns agent assignments plus complete profiles. Profiles do not inherit from or merge with other profiles. Each profile declares namespaces, and every namespace must select an explicit backend.kind: mcp_provider, controller_execution, or tool_vm_runner. Each namespace carries tools.allow / tools.deny visibility selectors plus calls.withoutApproval and calls.requiresApproval call selectors. Namespaces absent from the profile are denied. The controller approval surface handles managed calls.requiresApproval; calls.withoutApproval permits direct managed calls. Any managed namespace that effectively admits a tool through calls.requiresApproval requires zone approvalAccess. Static validation and Gateway preflight fail closed when approvalAccess is absent; agent-vm does not infer a default. Denied tools do not enter the agent's catalog or search index.

		For standalone or external MCP Portal, mcp.config.jsonc owns upstream MCP providers and mcp-portal.config.jsonc owns agent assignments, complete MCP profiles, call policy, and optional external proxy authentication. Bearer credentials, HMAC approval tokens, credentialVersion, and externalAuth belong only to this standalone surface.

	Authored config is JSONC. $schema points at local config/schemas/*.schema.json files generated by agent-vm init. schemaVersion is the runtime compatibility gate.

	MCP JSON Schema is canonical for upstream MCP provider calls. Zod is derived for validation and helper code. Portal-neutral contracts used by Tool Portal and controller execution boundaries are Zod v4 schemas first, with JSON Schema generated from Zod for protocol surfaces. Invalid call arguments and schemas that cannot be converted return structured errors without calling upstream. Tool VMs can use the mcp-portal helper package but do not receive upstream MCP credentials.

	Prefer http-mediation for MCP provider API keys, including stdio providers, when the provider sends the env value in outbound HTTP headers or other Gondolin-supported request locations. The MCP server sees a placeholder env value; Gondolin swaps it for the real secret only for configured hosts. Use raw env injection only as an explicit exception for providers that cannot operate with placeholders.

	Store MCP provider secrets as raw values. Omit \`format\` when the upstream expects the raw value. Use \`format: { "kind": "bearer" }\` when an upstream expects Bearer presentation, or \`format: { "kind": "prefix", "prefix": "Token" }\` for provider-specific schemes. Prefix presentation inserts exactly one ASCII space between the prefix and the raw secret or mediated placeholder, and the prefix itself must not contain whitespace.

		Run agent-vm validate --mcp-live after editing managed MCP providers or Tool Portal profiles. Static validate checks the managed mcp.config.jsonc and tool-portal.config.jsonc schema and materialization. Live validate follows only active Tool Portal namespaces whose backend.kind is mcp_provider, starts their referenced MCP providers, runs tools/list, and reports provider namespace, transport, phase, and hints for failures. Providers configured in mcp.config.jsonc but not referenced by an active mcp_provider namespace are outside that validation run.

	Read-only/destructive annotations are trusted only for configured MCP-provider namespaces. Managed namespaces must be explicitly selected through calls.withoutApproval or calls.requiresApproval.
	Channel-native approval settings, such as Discord approver user IDs, remain deployment-owned.

	MCP provider URLs must use http or https. Loopback and private-network upstream URLs are allowed because authored config is trusted deployment config and sidecar/local MCP providers are a supported shape. Do not import untrusted MCP provider config directly; if config trust changes, add an explicit per-provider network allowlist before accepting private-network targets.

Credential redaction is not general PII filtering. Catalogs redact exact configured secrets only; outputs and errors also redact credential-shaped text. Treat upstream tool response content as agent-visible unless a deployment adds future response middleware policy.
`,
			),
		},
		{
			relativePath: 'docs/manual/agent-worker.md',
			content: generatedPage(
				'Agent Worker Gateway',
				`
Worker gateways run task VMs with explicit phases: plan, work, review, and wrapup.
Repo resources live under .agent-vm inside target repos and are refreshed with agent-vm resources update.
Worker repo edits happen under /work/repos/<repoId> inside the VM. The controller keeps host gitdirs separate for authenticated git operations.
`,
			),
		},
		{
			relativePath: 'docs/manual/secrets.md',
			content: generatedPage(
				'Secrets And Runtime Auth',
				`
Secrets are declared in ${options.systemConfigPath}.
Use http-mediation for service tokens that should be swapped into outbound requests by the controller.
Use env only when the gateway process itself must read the raw value.
Do not bake secrets into Dockerfiles or images.
For Tool VM-reaching mediated secrets, agentAccess is required and the zone must declare agents. Use agentAccess: "all" only for a deliberate all-declared-agents placeholder, or a non-empty agent list such as ["sun"] for per-agent delivery. The controller filters by agentId before resolving secret refs, so non-matching agents do not cause scoped refs to be read. For audience "both", agentAccess scopes Tool VM delivery only; gateway mediation remains zone-wide.

Zones scaffold controller SSH adminAccess as mode: "none" because secret-backed admin SSH requires an operator-created secret. To protect controller-mediated SSH, create the secret first, then change zones[].adminAccess to mode: "secret" with a real secret reference.
Use agent-vm controller ssh --zone <zoneId> for a gateway admin shell. OpenClaw admin commands source the token named by gateway.controlAuth.secret.
Hermes admin shells load HERMES_HOME, the Hermes CLI path, and Gondolin CA bundle variables without loading raw framework secrets. Run native commands such as hermes auth add <provider> inside that shell.
Use agent-vm controller ssh --zone <zoneId> --all-secrets only when the shell must inspect or debug every raw gateway environment secret.
Controller SSH opens an interactive shell only. Do not use it as a one-shot command runner, and do not try to print raw SSH commands from the CLI.
Use agent-vm auth 1password <op-ref-or-url> --config ${options.systemConfigPath} to read a 1Password service-account token with op read and store it in the configured macOS Keychain service/account. Omit the ref/url only when pasting the token interactively.
For OpenClaw provider auth flows, prefer agent-vm auth openclaw login <provider> --zone <zoneId> --all-configured-profiles. This logs in each configured gateway.authLogin.providers.<provider>.profileIds entry for the configured gateway.authLogin.defaultAgent and verifies the profiles afterward. Use --dry-run to print the resolved plan without opening SSH. For custom one-off auth, pass --agent <agentId> with one or more --profile-id values, or use agent-vm controller ssh --zone <zoneId> and run OpenClaw auth manually.
Native Codex-runtime agents use agent-vm auth codex-harness --zone <zoneId> --agent <agentId>.
Managed OpenClaw gateway builds install the native Codex CLI version pinned by managed-images.json so codex-harness auth can run inside the gateway VM. If a deployment overrides the generated Dockerfile, install @openai/codex in that image before running codex-harness auth.
Tool VMs and agent sandboxes do not receive gateway SSH secrets.
`,
			),
		},
		{
			relativePath: 'docs/manual/tool-access.md',
			content: generatedPage(
				'Tool Access And Isolation',
				`
OpenClaw zones choose Tool VM images with defaultToolVmProfile and optional agentToolVmProfiles.

There are three isolation layers:

1. Auth-based isolation.
   The binary may exist for every agent, but only an agent's scoped sandbox contains credentials or seeded profile files. This is cheap, but the binary is still callable.

2. OpenClaw tool allowlists.
   Per-agent tool policy can stop an agent from invoking certain named tools. This is useful, but it is not binary-level isolation if a broad shell tool can still run arbitrary commands.

3. Per-zone Tool VM images.
   Use separate zones when binary-level differences must also carry gateway lifecycle, channel, or zone-files isolation.

Managed OpenClaw zones may declare multiple trusted agents in zones[].agents. Use agentToolVmProfiles for per-agent Tool VM image selection inside the same zone, and use separate zones only when gateway lifecycle, channel, secret, or zone-files isolation matters more than sharing the gateway VM.
`,
			),
		},
		{
			relativePath: 'docs/manual/channels.md',
			content: generatedPage(
				'Gateway Channels',
				`
Discord is configured by the deployment, not by agent-vm defaults.

To add a channel:
1. Add the channel config in openclaw.json.
2. Add required secrets in ${options.systemConfigPath}.
3. Add egressHosts and any required websocketUpgrades entries for the channel endpoints.
4. Run agent-vm validate, then rebuild the gateway image and run agent-vm doctor after the deployment is ready.

Discord recipe:
- Add DISCORD_BOT_TOKEN as a zone secret.
- Add discord.com, *.discord.com, discord.gg, *.discord.gg, discord.media, *.discord.media, discordapp.com, *.discordapp.com, and *.discordapp.net to egressHosts with audience both.
- Discord media downloads use OpenClaw's Discord media SSRF policy, not tools.web.fetch.ssrfPolicy. If media logs show blocked URL fetch for cdn.discordapp.com or media.discordapp.net, verify the installed agent-vm version emits ::ffff:198.18.0.1 synthetic AAAA for Gondolin TCP-host VMs before adding broader OpenClaw hostname bypasses.
- Add websocketUpgrades for Discord Gateway WebSockets: allow wss://gateway.discord.gg/ and wss://gateway-*.discord.gg/ for audience gateway.
- Do not add raw TCP entries for Discord Gateway WebSockets. Use native Gondolin WebSocket upgrades.
- Enable channels.discord in deployment-owned openclaw.json.
- Do not add Discord under plugins.allow or plugins.entries.
- agent-vm build installs @openclaw/discord for managed OpenClaw images when channels.discord is enabled.
- Pin @openclaw/discord in vm-images/gateways/openclaw/overlay.jsonc only when the deployment needs to override the managed default version.
- Do not add runtimeAuthHints to OpenClaw zones; they are worker gateway runtime instructions only.
- Tool VM secrets must use injection http-mediation and declare agentAccess as "all" or a non-empty list of declared zone agent ids. source environment is allowed only as the controller-side source for mediated Tool VM secrets; never use injection env for Tool VM audience.

Managed Hermes profile secrets:
- Give every declared agent matching entries in gateway.profilesByAgent and gateway.profileSecretProjectionsByAgent.
- Map the API_SERVER_KEY target to one distinct injection env, audience gateway zone secret per agent. The separate root source named API_SERVER_KEY remains reserved and cannot be reused by a named profile.
- Map the DISCORD_BOT_TOKEN target to one distinct injection env, audience gateway zone secret per agent.
- Use each profile's own API key for /p/<profile>/... requests. Unprefixed root routes continue to use the root listener key.
- The only additional profile environment targets allowed for Hermes are DISCORD_ALLOW_BOTS and DISCORD_BOTS_REQUIRE_INLINE_MENTION; each source must use injection env and audience gateway.
- DISCORD_ALLOW_BOTS accepts none (safe default), mentions (only explicitly mentioned bot messages), or all. DISCORD_BOTS_REQUIRE_INLINE_MENTION=true adds a literal inline @mention gate for bot-authored messages.
- Map other profile credential targets to Gateway-reaching http-mediation sources; Hermes receives only their opaque placeholders.
- Agent VM writes complete target maps only to the exact memory-backed profiles/<profile>/.env files before stock Hermes starts.
- Keep common non-secret policy in the dedicated gateway.config config.yaml directory mounted read-only at /etc/hermes/config.yaml. HERMES_MANAGED_DIR remains unset; root/default and named profile homes remain direct stateDir RealFS.
- New named profiles receive native config.yaml with platforms.api_server.enabled: false because the default profile owns Hermes's single HTTP listener; the shared listener still authenticates /p/<profile>/ with that profile's API_SERVER_KEY. Existing named profile configs must contain the same explicit disable or Agent VM rejects them before boot instead of rewriting authored bytes.
- Durable root/profile .env and secret-bearing native Hermes config are rejected. Remove known legacy files explicitly; do not add migration or copy-back behavior.
- Do not configure Hermes profiles to reply to one another in a shared Discord channel. Upstream warns that reply pings can satisfy mention gates and create acknowledgement/feedback loops; any beta probe is bounded validation only, not a supported topology.
`,
			),
		},
		{
			relativePath: 'docs/manual/runtime-paths.md',
			content: generatedPage(
				'Runtime Paths',
				`
Managed OpenClaw Tool VMs run commands in rootfs/COW /work by default. /work is disposable execution space and is deleted with the Tool VM.
/workspace is the current agent's filtered durable RealFS workspace selected by the controller from stable agent identity. It is the only durable agent workspace exposed to that Tool VM.
/gitdirs/workspace.git is present only when the current agent enables zones[].agents[].workspaceGit. No parent Git directory or sibling agent Git database is exposed.
Managed Tool VMs do not currently expose a generic /agent-vm path. Worker task VMs retain their separately owned generated /agent-vm inputs.
/state is controller/gateway plumbing, not the primary place for agent docs.
worker repo edits live under /work/repos inside Worker gateway task VMs.
Worker gateway task VMs use /work/tmp for temporary files and /work/cache for disposable package-manager cache.
OpenClaw gateway VMs use /work/tmp and /work/cache for disposable runtime work; persistent zone files live at /zone and are backed by the derived zoneFilesDir.

OpenClaw SDK compatibility note: OpenClaw may call the agent's Gateway path workspaceDir. In managed mode it must identify the configured agent workspace under /zone/agents/<agentId>. The plugin validates that native origin, translates it immediately to stable agent identity, and never sends the Gateway path or a host path as Tool VM storage authority.
Controller startup acquires <controllerRuntimeDir>/vm-ownership/controller-ownership.lock before secret resolution or VM reconciliation and holds it until shutdown completes. A second controller or offline cleanup process cannot enter destructive reconciliation while that lock is held.
The lock is mutual exclusion, not destruction evidence. The controller persists schema-v2 Tool records at controllerStateDir/zones/<zoneId>/tool-leases/<recordId>.json and the Gateway record at controllerStateDir/zones/<zoneId>/gateway-runtime.json. They bind the deployment and Gateway parent to exact VM id, pid, and process-start identity cleanup evidence. Controller restart adopts no VM: it destroys verified Tool runners before their Gateway, then starts a fresh tree. Unknown or mismatched identity preserves the record and refuses replacement or Tool slot reuse. HTTP health and telemetry remain diagnostic only.

Per-agent workspace Git:
- Configure workspaceGit on the owning zones[].agents[] entry; absence disables Git.
- mode=local creates an isolated workspace Git database without a push capability.
- mode=remote creates the same isolated database and exposes the controller-owned workspace_git_push Tool Portal action for that agent.
- Tool VM Git SSH remains read-only: fetch is allowed and direct push is denied.
- The controller uses host-only HTTPS credentials, expected-head/CAS checks, and rejects a push to the configured default branch.
- Backups include durable workspace files and exclude zoneRuntimeDir Git metadata.
`,
			),
		},
		{
			relativePath: 'docs/manual/per-agent-setup.md',
			content: generatedPage(
				'Per-Agent Setup',
				`
Managed OpenClaw gateway zones may declare multiple trusted agents. Use scope=agent so OpenClaw resolves each agent to its stable work mount; agent-vm still keys Tool VM lease identity by zone and agent id.

Per-agent auth isolation works by using agent-vm auth codex-harness for native Codex CLI auth and gateway.authProfilesByAgent for intentionally separate prebuilt OpenClaw auth profiles. Agent-authored durable files belong under zoneFilesDir/agents/<agentId> and appear through the selected filtered /workspace projection; framework-private auth state remains in the Gateway and is not projected into Tool VMs.
Shared OpenClaw provider auth works through gateway.authLogin. agent-vm auth openclaw login <provider> --all-configured-profiles logs in each configured gateway.authLogin.providers.<provider>.profileIds entry for gateway.authLogin.defaultAgent and verifies those profile IDs afterward. Use --dry-run before a refresh when you want to inspect the target agent and profile list.
Native Codex-runtime agents use codex-harness --all-agents to run one device-auth session per agent listed in the zone's system config. Use --agent <agentId> for a one-off login outside that configured list.

OpenClaw tool allowlists are a policy layer. They do not remove binaries from the Tool VM image if a broad shell tool can still run them.

Binary-level isolation requires different Tool VM images. Use agentToolVmProfiles for per-agent image differences inside one managed OpenClaw zone when gateway lifecycle can be shared. Use separate zones when the gateway VM, channel, secret, or zone-files boundary must also be separate.

Git workflow with zones[].agents[].workspaceGit:
- Agents may inspect, switch branches, merge, stage, and commit their own /workspace changes with normal Git commands.
- Do not run raw git push. Tool VM Git SSH is read-only and Tool VMs do not receive GitHub credentials.
- Remote mode exposes the controller-owned workspace_git_push Tool Portal action for the configured branch; local mode and absent workspaceGit expose no push action.
- The controller rejects the configured default branch. If it reports divergence, expected-head mismatch, or another rejection, stop and report the exact message.
`,
			),
		},
		{
			relativePath: 'docs/manual/migration-discord.md',
			content: generatedPage(
				'Discord Migration',
				`
Agent-vm defaults are channel-neutral. Existing Discord deployments keep Discord by owning the channel config:

1. Run agent-vm migrate images if the deployment still references Dockerfiles.
2. Keep Discord enabled under channels.discord in config/gateways/<zone>/openclaw.json.
3. Keep DISCORD_BOT_TOKEN in ${options.systemConfigPath} zone secrets.
4. Keep discord.com, *.discord.com, discord.gg, *.discord.gg, discord.media, *.discord.media, discordapp.com, *.discordapp.com, and *.discordapp.net in egressHosts with audience both.
5. Delete any stale raw WebSocket TCP passthrough field from ${options.systemConfigPath}.
6. Use websocketUpgrades for wss://gateway.discord.gg/ and wss://gateway-*.discord.gg/. Do not add raw TCP entries for Discord Gateway WebSockets.
7. Run agent-vm validate before rebuilding or restarting.

Do not reintroduce Discord into agent-vm init defaults. Use this page as the deployment recipe.
`,
			),
		},
		{
			relativePath: 'docs/manual/troubleshooting.md',
			content: generatedPage(
				'Troubleshooting',
				`
Run agent-vm validate after config edits.
Run agent-vm doctor before starting or after changing images, secrets, or channel plugins.
Run agent-vm manual update after upgrading agent-vm to refresh this manual.

Discord media symptom:
- Log text: blocked URL fetch, resolves to private/internal/special-use IP address, cdn.discordapp.com, or media.discordapp.net.
- First check: the gateway is running an agent-vm version whose Gondolin adapter emits ::ffff:198.18.0.1 for synthetic AAAA when tcpHosts are enabled.
- Expected behavior: normal fetches use the IPv4/per-host synthetic path. curl -6 inside the guest may fail because this is not general guest IPv6 egress.
- Safer fix order: adapter synthetic DNS fix first, Discord egressHosts second, exact browser.ssrfPolicy.allowedHostnames bypass only after naming the broader private-IP-check tradeoff.
- Non-fix: Gondolin allowedInternalHosts only affects Gondolin HTTP hooks. It does not change OpenClaw Discord media SSRF and does not apply to raw tcpHosts.
`,
			),
		},
	];
}
