export const GENERATED_MANUAL_MARKER = 'Generated by agent-vm manual. Do not edit by hand.';

export interface ManualTemplateOptions {
	readonly defaultZoneId: string;
	readonly systemConfigPath: string;
}

export interface ManualTemplateFile {
	readonly content: string;
	readonly relativePath: string;
}

function generatedPage(title: string, body: string): string {
	return `<!-- ${GENERATED_MANUAL_MARKER} -->

# ${title}

${body.trim()}
`;
}

export function buildAgentVmAgentsTemplate(options: ManualTemplateOptions): string {
	return generatedPage(
		'Agent Instructions',
		`
This deployment uses agent-vm. Start with docs/manual/README.md, then drill into the specific manual page for the task.

Primary config:
- System config: ${options.systemConfigPath}
- Default zone: ${options.defaultZoneId}

Use docs/manual/layout.md before moving files or changing generated folders.
Use docs/manual/image-versioning.md before changing agent-vm package pins, Hermes image inputs, managed image pins, or generated Dockerfiles.
Use docs/manual/tool-vm-leases.md before changing agent-vm Tool VM lease identity, renewal, or reuse behavior.
Use docs/manual/gateway-ingress.md before changing gateway ports, Hermes API access, SSE/streaming behavior, WebSocket access, or serving additional webservers from inside a VM.
Use docs/manual/operations.md before debugging agent-vm controller health, gateway service health, lease-heartbeat, lease-renew, Tool VM SSH, or Gondolin tcpHosts timeouts.
Use docs/manual/observability.md before changing host observability, Victoria storage, OpenTelemetry collector ports, Hermes telemetry, or logging behavior.
Use docs/manual/mcp-portal.md before changing MCP providers, managed Tool Portal profiles, standalone MCP Portal profiles, MCP package pins, or live MCP validation.
Use docs/manual/tool-access.md before answering whether a tool binary, auth profile, or tool VM image should be agent-specific.
Use docs/manual/channels.md before helping a human configure Discord or another Hermes channel.
Use docs/manual/runtime-paths.md before answering where files appear inside VMs or how managed Tool VMs separate durable /workspace, disposable /work, and optional /gitdirs.
Use docs/manual/per-agent-setup.md before changing Hermes profile assignments or per-agent tool/auth isolation.

Do not assume Discord is enabled by the framework. Channels and channel secrets are deployment-owned.
Do not silently edit privileged host/deployment config. Explain the proposed Dockerfile, secret, egressHosts, websocketUpgrades, or Hermes config change and wait for the human to ask you to apply it.
`,
	);
}

export function buildManualTemplateFiles(
	options: ManualTemplateOptions,
): readonly ManualTemplateFile[] {
	return [
		{
			relativePath: 'docs/manual/README.md',
			content: generatedPage(
				'agent-vm Deployment Manual',
				`
This manual is generated from the installed agent-vm package. It is the deployment-local guide for coding agents helping end users set up and operate agent-vm deployments.

Read in this order:
1. layout.md explains generated folders and ownership.
2. image-versioning.md explains package pins, managed image pins, overlays, and generated Dockerfiles.
3. tool-vm-leases.md explains agent-keyed Tool VM lease identity and reuse.
4. hermes.md explains the managed Hermes Gateway and its configuration boundaries.
5. gateway-ingress.md explains host-facing Hermes ingress, streaming, WebSockets, and the boundary for additional guest webservers.
6. observability.md explains managed or external host observability setup, build-time Docker Compose startup for managed stacks, controller startup behavior, and telemetry safety rules.
7. mcp-portal.md explains managed Tool Portal policy, standalone MCP Portal policy, progressive MCP discovery, and gateway-owned MCP auth.
8. tool-access.md explains binary, capability, and zone/image isolation.
9. channels.md explains how deployments configure Discord or other Hermes channels.
10. runtime-paths.md explains /workspace, /work, optional /gitdirs, and other in-VM paths.
11. per-agent-setup.md explains Hermes profile layout and per-agent tool access choices.
12. secrets.md explains runtime auth and HTTP mediation.
13. operations.md explains start, graceful stop, scoped offline cleanup, health snapshots, lease-heartbeat, lease-renew, gateway-service health, and gateway-to-controller control-session checks.
14. troubleshooting.md explains the first checks for validation, Hermes configuration, and runtime health failures.

Local deployment notes belong in docs/manual/local-notes.md or another non-generated file.
`,
			),
		},
		{
			relativePath: 'docs/manual/layout.md',
			content: generatedPage(
				'Generated Layout',
				`
${options.systemConfigPath} is the controller config. Agent-vm-authored config is JSONC so short local comments are allowed.
config/gateways/<zone>/hermes-managed/config.yaml is the deployment-owned managed Hermes policy input. The generated directory contains only config.yaml.
config/gateways/<zone>/mcp.config.jsonc is the upstream MCP provider catalog for a managed Hermes zone.
config/gateways/<zone>/tool-portal.config.jsonc is the managed Tool Portal agent/profile and backend policy.
config/gateways/<zone>/oauth.config.jsonc optionally enables controller-owned Google OAuth for that managed Hermes zone. It uses direct tailnet HTTPS on port 18900, a 1Password-held KEK, encrypted controller-state SQLite, and account-profile-scoped Gog access. OAuth consent never bypasses Tool Portal visibility or approval policy.
config/gateways/<zone>/worker.jsonc is Agent Worker gateway config when the zone type is worker.
vm-images/ contains deployment-owned Gondolin build-config.jsonc files and small managed image overlays.
agent-vm owns the gateway/tool base image recipes and pins the managed GHCR base layer version.
storageRootDir is the required, final deployment storage root. Generated local, user-dir, and pod scaffolds scope it by host.projectNamespace. The controller loads that full path and derives cacheDir, controllerStateDir, controllerRuntimeDir, and each zone's stateDir, optional zoneFilesDir, and zoneRuntimeDir without appending the namespace again.
stateDir is <storageRootDir>/<zoneId>/state and stores durable gateway state.
zoneFilesDir stores durable shared zone files and per-agent workspaces for managed Gateway zones. It is derived at <storageRootDir>/<zoneId>/zone-files. Each configured agent owns zoneFilesDir/agents/<agentId>. Worker zones have no active zoneFilesDir.
gateway.backupIdentity selects the host-resolved Age identity required by backup create and restore. Backup list does not resolve it, and there is no implicit identity fallback.
cacheDir is <dirname(storageRootDir)>/cache and is the one shared rebuildable cache. VM images live under cacheDir/vm-images/<fingerprint>; deployment-scoped Docker contexts and framework caches live under cacheDir/deployments/<deploymentCacheKey>.
generatedDir is <storageRootDir>/generated and stores only small reproducible metadata such as image selections and Gateway-effective config.
controllerStateDir is required as a derived controller capability at <storageRootDir>/controller-state and stores host-controller-only durable authority.
controllerStateDir is never mounted into a Gateway or Tool VM and must remain disjoint from config, cache, runtime, Gateway state, backup, observability, and mount-source paths.
All controller records live below the one host-controller-owned root at controllerStateDir/zones/<zoneId>: approvals/, credentialed-runtimes/<recordId>.json, gateway-runtime.json, tool-leases/<recordId>.json, and worker-tasks/<taskId>/gateway-runtime.json.
controllerRuntimeDir is <storageRootDir>/controller-runtime and stores the controller ownership lock, health evidence, and generated observability files.
zoneRuntimeDir is <storageRootDir>/<zoneId>/runtime and stores zone logs, workspace Git databases, Worker task runtime, and control-session material outside normal backup.
When zones[].agents[].workspaceGit is enabled, its isolated Git database lives at zoneRuntimeDir/gitdirs/agents/<agentId>/workspace.git while the durable workspace remains under zoneFilesDir/agents/<agentId>.

Author JSONC for human-owned agent-vm config. Runtime files such as /state/effective-worker.json, task event JSONL, runtime records, and API bodies stay strict JSON.
Hermes gateway VMs mount zoneFilesDir at /zone.
Managed Hermes Tool VMs expose only the selected agent's filtered durable workspace at /workspace. They do not mount the whole /zone tree.
Managed Tool VMs use rootfs/COW /work for disposable execution and optionally expose only the selected workspace Git database at /gitdirs/workspace.git. No generic /agent-vm surface is mounted unless a future contract names its exact generated inventory and owner.
Worker task VMs keep repo files on rootfs/COW at /work/repos.
Hermes gateway VMs use /work/tmp and /work/cache for disposable runtime work.
`,
			),
		},
		{
			relativePath: 'docs/manual/image-versioning.md',
			content: generatedPage(
				'Image Versioning',
				`
There is one owner for each version decision.

package.json owns which installed @agent-vm/* package version this deployment uses. Upgrade agent-vm by changing package.json and the lockfile, then run agent-vm manual update and agent-vm build from that installed package.

controller start refuses a stale prepared Gateway image when its fingerprint does not match the currently installed agent-vm runtime and build inputs. Startup does not rebuild images automatically; run agent-vm build from the installed package, then retry controller start.

The installed @agent-vm/agent-vm package owns managed-images.json. That manifest selects the managed GHCR base image tags and package defaults for Worker Gateway and Tool VM images. Deployment repos should not copy or edit managed-images.json.

The installed @agent-vm/hermes-gateway package owns the Hermes image recipe and immutable upstream distribution pin. A Hermes upstream version, source revision, or container digest change is an agent-vm release change, not a deployment overlay change.

vm-images/.../overlay.jsonc owns deployment image additions. Use extraAptPackages for apt packages, copy for deployment files, runAfterBase for post-base commands, and packageOverrides.npm only for deliberate exact image-local npm package pins. Do not restate the managed default package set in deployment overlays, and do not install @agent-vm/* packages through packageOverrides.

Do not edit generated Docker build contexts under cacheDir/deployments/<deploymentCacheKey>/docker-contexts/... by hand. They are disposable build output. If a generated Dockerfile contains the wrong package version, change package.json or the overlay that produced it, then rebuild.

Agent VM stores complete immutable VM images once under cacheDir/vm-images/<fingerprint>. A deployment's small image selections live under storageRootDir/generated/image-selections. Controller and Tool VM startup validate those selections and tell you to run agent-vm build when one is missing or stale.

New images are checksum-verified before publication. Reuse validates manifest and file structure without hashing large images again; it does not detect every later binary corruption. Never repair or replace shared fingerprint directories by hand.

Uncached image publication requires Python 3 on the controller host and native no-replace rename support on macOS or Linux. Missing support fails closed before image construction. Keep declared init scripts, copied files/directories, and custom helper binaries stable during a build; their content participates in shared-image identity.

For managed Worker and Tool VM images, managed package defaults come from managed-images.json and overlay packageOverrides.npm wins by package name inside the selected image profile. Generated Dockerfiles receive the resolved package specs only as disposable output.

For Hermes images, the generated deployment Dockerfile comes from the installed Hermes recipe and embeds the installed agent-vm package version plus the immutable Hermes distribution inputs. Review the generated recipe and build plan before debugging Docker output. Do not copy the recipe into a second version owner.
`,
			),
		},
		{
			relativePath: 'docs/manual/tool-vm-leases.md',
			content: generatedPage(
				'Tool VM Lease Identity And Reuse',
				`
Managed Hermes Tool VMs are agent-keyed: one compatible Tool VM per zone and Agent VM agent id.
The Hermes integration authenticates the native profile, selects its controller-authored projection, and sends typed requests to the common Tool Portal service over the private UDS. Framework session metadata does not choose, identify, renew, list, log, or store Tool VM leases.
The controller resolves the stable agent identity to controller-owned workspace, optional workspace Git, and Tool VM profile capabilities. Caller-supplied Gateway or host paths do not select storage. The lease identity remains zoneId + agentId, not a path string.
TCP slots are capacity; they are not identity.
The common Tool Portal service owns current-epoch agent bindings, per-agent strict SSH connections, Sandbox operations, and active-use tracking. It renews reusable bindings and heartbeats active shell/file/process operations over its private controller relationship so long commands are not reaped mid-run.
Health snapshots include lease-renew and lease-heartbeat observations. Both keep lease state alive when successful, but they prove different things: lease-renew proves an idle cached lease can be reused, while lease-heartbeat proves an active operation still has a live private control-session path.

If the Tool Portal service observes stale Tool VM SSH evidence, it retires the old binding before the next operation and asks the controller for current replacement access. The controller re-checks old-binding authority, current caller context, session fence, workspace, profile, and agent ownership before publishing new service-private SSH material.
The old lease id is correlation only, not authority. No later shell, file, exec, heartbeat, or finalize work may use the old lease id or old SSH identity after stale evidence. Framework integrations never receive lease ids or SSH material.

Example:
- shravan agent uses agentId=shravan.
- alevtina agent uses agentId=alevtina.
- Each agent gets its own compatible Tool VM lease with its filtered durable workspace at /workspace and disposable rootfs/COW work at /work.
- Managed Hermes supports multiple declared agents in the same zone when profilesByAgent and profileSecretProjectionsByAgent are explicit and consistent.
- defaultToolVmProfile is the fallback Tool VM image; agentToolVmProfiles can select a different image per declared agent.
- Use separate zones when gateway lifecycle or channel isolation matters more than sharing a gateway VM.
- Agent-authored durable files live in that agent's zoneFilesDir/agents/<agentId> workspace. Hermes profile-private framework state remains under stateDir/profiles/<profileName> and is not projected into Tool VMs.
- Use separate zones when gateway lifecycle isolation or shared-zone cost is worse than another gateway VM.
`,
			),
		},
		{
			relativePath: 'docs/manual/operations.md',
			content: generatedPage(
				'Operations',
				`
Use graceful controller stop first:

agent-vm controller stop --config ${options.systemConfigPath}

If the controller HTTP server is broken or gone, use scoped offline cleanup:

agent-vm controller cleanup --config ${options.systemConfigPath} --zone ${options.defaultZoneId}

Offline cleanup first acquires the same deployment-wide ownership lock held by a running controller, then refuses to run while the configured controller health endpoint is reachable. --force skips only that advisory health probe; it never bypasses the ownership lock or exact-evidence checks.

The ownership lock provides mutual exclusion; it is not destruction evidence. Cleanup validates credentialed runtime records under controllerStateDir/zones/<zoneId>/credentialed-runtimes/<recordId>.json and Tool records under controllerStateDir/zones/<zoneId>/tool-leases/<recordId>.json before controllerStateDir/zones/<zoneId>/gateway-runtime.json. Records bind controller or Gateway ownership to exact VM id, pid, and process command/start identity as applicable. The controller revalidates the live process and endpoint, never adopts an old VM, and deletes a record only after exact process and endpoint absence is proven.

Old, malformed, mismatched, occupied-endpoint, or otherwise unproven records fail closed and remain for diagnosis. Unknown identity preserves the evidence and prevents Gateway replacement or Tool TCP-slot reuse. Gateway subtree cleanup runs at most four child destroys concurrently, and the whole subtree has a 300 second deadline. An incomplete disposition leaves the old Gateway owner-unsafe and refuses a replacement until cleanup is proven complete.

Do not use broad QEMU process kills as normal deployment workflow. Multiple agent-vm installations can run on one host, and broad process matching can kill the wrong installation.

Local package scripts should be thin wrappers around these commands. Deployment repos should not copy process-fencing logic.

OpenClaw predecessor shutdown boundary:
1. Before installing the Hermes-only release or replacing deployment config, use the still-installed pre-cutover release and its valid config to stop the controller-managed OpenClaw Gateway.
2. Prove its Tool VM lease records and Gateway runtime record are cleared and the configured ingress is no longer owned.
3. Only then replace the package train and author a new Hermes or Worker config. The new release does not parse, migrate, or delete predecessor state.

Health model:
- GET /health is the global agent-vm controller liveness endpoint.
- GET /zones/<zoneId>/health is an on-demand live readiness probe.
- GET /zones/<zoneId>/service-health is an on-demand live gateway-service liveness probe.
- GET /zones/<zoneId>/health-snapshot is an in-memory zone health view.
- agent-vm controller health --config <system-config> --zone <zoneId> prints the live readiness probe result.
- agent-vm controller service-health --config <system-config> --zone <zoneId> prints the live gateway-service liveness probe result.
- agent-vm controller health-snapshot --config <system-config> --zone <zoneId> prints the in-memory zone health snapshot.
- Health snapshots separate gateway infrastructure, gateway service, channel-provider, and Tool VM lease health.
- gateway-service-health means the agent-vm controller can probe Hermes service liveness through the gateway VM runtime at /health.
- gateway-control-session means the agent-vm controller owns a private Socket.IO control session into the gateway VM through Gondolin ingress.
- agent-channel-provider-health means the Gateway framework reports whether an agent channel provider can communicate. The controller reads only generic health values such as healthy, transitioning, unhealthy-recoverable, and unhealthy-unrecoverable.
- gateway-recovery means the controller attempted an automatic whole-Gateway VM restart or cold start after Gateway service, control-session, or sibling-lifecycle evidence required replacement.
- gateway-recovery-suspended means repeated automatic restarts failed and the controller paused further auto-recovery for that zone until the reset window expires.
- lease-heartbeat means an active Tool VM operation can refresh its active use.
- lease-renew means an idle cached Tool VM lease can be reused.
- tool-vm-ssh means command, file-bridge, finalize, or probe SSH operations on the gateway-to-Tool-VM path.
- tool-vm-ssh lifecycle events distinguish Tool Portal service observations from controller_final decisions. A controller_final stale_to_reacquired event proves the controller accepted one replacement transition for the old lease and records old/replacement lease correlation using redacted public ids.

Health snapshots and bounded event history are in-memory controller state for live diagnosis. Accepted health and recovery events are also appended to <controllerRuntimeDir>/controller-health/events.jsonl as diagnostic evidence; that log and exported telemetry are not lifecycle authority. The controller owns lifecycle decisions; schema-v2 runtime records plus revalidated process and endpoint identity are durable crash-cleanup evidence.

By default, controller.health.gatewayServiceAutoRestart observes gateway-service and gateway-control-session degradation. The managed Tool Portal and selected framework processes are VM-boot siblings; neither supervises or restarts the other. Unrecoverable sibling or control-session failure retires the Gateway epoch and uses whole-Gateway VM recovery. The same recovery path can cold-start a failed or stopped Gateway when current ownership checks prove it is safe. Gateway recovery has a 61 minute cooldown per zone and a 10 minute restart deadline. Gateway replacement releases active Tool VM leases for that zone first, so in-flight tool work is interrupted instead of keeping stale SSH state alive. After 3 consecutive failed automatic Gateway recoveries, the controller records gateway-recovery-suspended and pauses further auto-recovery for that zone until the 24 hour reset window expires.

Channel-provider failures are diagnostic input only through the generic contract by default. A channel provider marked unhealthy-recoverable degrades readiness/status but does not restart the gateway unless controller health policy explicitly enables restartGatewayOnRecoverable. A channel provider marked unhealthy-unrecoverable is surfaced for operator diagnosis and does not restart the gateway by default. Provider-specific details stay in the event payload; the controller must not branch on Discord, Slack, or other platform-specific names.

secret-resolution-failed is a recovery blocker, not proof of the original outage cause. Show it as the reason a start, restart, credentials refresh, or cold-start cannot proceed now unless durable lifecycle evidence proves the outage began during that operation.

Use agent-vm controller credentials check --zone <zone> to verify gateway secret resolution without contacting the controller or restarting the gateway. Use credentials refresh only when the operator intentionally wants a credential refresh and zone runtime restart.

Tool VM lease failures retire or quarantine one lease before gateway restart. A tool-vm-ssh failure should not be treated as gateway infrastructure failure unless lease-manager or gateway control-session health also proves a broader gateway problem.

Health timeouts are operation-specific. Short health probes should fail quickly; git push/pull and lease-create get longer budgets. Do not assume every abort means the work should be killed.
`,
			),
		},
		{
			relativePath: 'docs/manual/hermes.md',
			content: generatedPage(
				'Hermes Managed Gateway',
				`
Agent-vm provides VM lifecycle, durable state and workspace mounts, TCP/HTTP mediation, image build, controller authority, and Tool VM leases. Hermes owns its native agents, profiles, sessions, models, and channels.

Managed Gateway boot starts one common Tool Portal service process beside one Hermes framework process. The Hermes adapter authenticates the routed native profile and sends Capability API and SSH Sandbox API requests through one GatewayRuntimeClient over the private UDS.

The controller remains durable lease authority. ToolPortalService owns current-epoch bindings, per-agent strict SSH connections, active uses, and Sandbox operations. Hermes receives API results, not lease ids or SSH material. Command stdout, stderr, and file traffic flow through the private UDS and the service-owned gateway-to-Tool-VM SSH data path.

Hermes application activity is not infrastructure health proof. Use agent-vm health snapshots to distinguish Hermes service health, the gateway-to-controller control session, lease-heartbeat, lease-renew, and Tool VM SSH health. Channel-provider details stay inside Hermes payloads; the controller branches only on generic channel-provider health: healthy, transitioning, unhealthy-recoverable, and unhealthy-unrecoverable.

The generated managed policy at config/gateways/<zone>/hermes-managed/config.yaml must keep agent-vm-tool-portal enabled and contains no credentials. Root and named native Hermes config.yaml files live in the zone's durable stateDir. Agent VM creates missing files, validates them before boot, and rejects native secrets, credential fields, Discord enablement fields, and additional port-binding platforms in the managed policy input.

Every zones[].agents[] entry must have one unique normalized gateway.profilesByAgent assignment and one gateway.profileSecretProjectionsByAgent map. Named profiles must explicitly set platforms.api_server.enabled: false because the root/default Hermes profile owns the one shared listener. The shared listener authenticates routed /p/<profile>/... requests with that profile's projected API_SERVER_KEY.

Use defaultToolVmProfile, agentToolVmProfiles, zones[].agents[].workspaceGit, leaseIdleTtl, and tcpPool from the current system config reference for exact field names. Run agent-vm validate after authored config changes and agent-vm doctor after rebuilding or starting the deployment.
`,
			),
		},
		{
			relativePath: 'docs/manual/observability.md',
			content: generatedPage(
				'Host Observability',
				`
Host observability is deployment-configured. Enable host.observability in ${options.systemConfigPath}. Per-zone observability supports managed Hermes gateways through Gondolin HTTP mediation. Each enabled zone configures separate framework and common Tool Portal signal policies under zones[].observability.services. The old collector route depended on raw Gondolin tcpHosts and must not be restored.

Use host.observability.stack.mode=managed when this deployment should own the local Victoria + OpenTelemetry Collector stack. In managed mode, host.observability.stack.scrubbing.responsibility defaults to agent-vm-managed-collector. Agent-vm build prepares the host stack when host.observability.prepareOnBuild is true and at least one selected managed Hermes zone has zones[].observability enabled. The build step renders docker-compose.observability.yml and otel-collector-config.yaml under controllerRuntimeDir/observability/<projectNamespace>, creates durable Victoria data directories under host.observability.dataDir, then runs docker compose up -d. Generated Compose services use restart: unless-stopped so Docker can restore them after daemon or host recovery. Use agent-vm build --no-observability to skip the host stack for one build run.

Use host.observability.stack.mode=external when a shared collector is already managed outside this deployment. External mode never renders or starts Docker Compose and does not require host.observability.dataDir or retention. Set host.observability.stack.scrubbing.responsibility=external-collector to make the external collector sanitization responsibility explicit, and keep that collector available on the configured loopback collector ports.

Controller startup does not start Docker Compose. With controllerStartPolicy=degraded, the controller binds and starts while it checks host observability readiness in the background. Managed mode checks the OpenTelemetry collector plus Victoria metrics, logs, and traces endpoints. External mode checks only the configured OpenTelemetry collector health endpoint. With controllerStartPolicy=require-ready, startup waits only for the configured total bounded readiness budget and fails if the configured collector or already-prepared managed stack is unavailable. With controllerStartPolicy=off, startup does not check host observability.

For managed mode, keep durable host.observability.dataDir outside storageRootDir. Victoria data is intentionally independent from rebuildable cache and disposable controller or zone runtime folders. Retention is configured separately for metrics, logs, and traces with period plus optional disk bounds.

Published ports bind to loopback only. Do not publish collector or Victoria ports on broad host interfaces unless a separate, authenticated access layer owns that exposure.

Enable zones[].observability only for managed Hermes zones that should export framework and Tool Portal diagnostics to the host collector. Worker zones reject it. The gateway sends OTLP to a synthetic collector host that agent-vm rewrites to the configured loopback collector. Tool VM SSH is the only managed gateway raw TCP exception.

Service identities are fixed: agent-vm-hermes and agent-vm-tool-portal. Do not author serviceName. Each producer suppresses content and baggage and uses its own fixed bounded lossy queue; collector scrubbing remains defense in depth.

Never log secrets, prompts, message bodies, tool payloads, cookies, authorization headers, token values, raw URLs with query strings, private keys, or command content. The managed OpenTelemetry collector drops known sensitive attributes before export and Victoria Logs ignores known sensitive fields, but that is defense-in-depth. External collectors must provide equivalent sanitization before storing or forwarding agent-vm telemetry. Source logging still owns the first safety boundary.
`,
			),
		},
		{
			relativePath: 'docs/manual/gateway-ingress.md',
			content: generatedPage(
				'Gateway Ingress And Serving',
				`
Agent-vm exposes Hermes gateway HTTP through Gondolin ingress. Keep three layers separate:

1. zones[].gateway.port is the host-facing Gondolin ingress listener.
2. Gondolin routes request path prefixes to guest loopback HTTP ports.
3. Hermes serves the root API listener and routed /p/<profile>/... endpoints from its guest gateway port.

The current Hermes gateway route is intentionally simple: agent-vm publishes one framework root route to the Hermes guest gateway port after both the framework and private control planes are admitted. The controller uses /health for Hermes readiness and gateway-service probes. Named profile requests use /p/<profile>/... and authenticate with that profile's projected API_SERVER_KEY; unprefixed root routes use the root listener key.

SSE and streaming responses need incremental forwarding. Agent-vm keeps Gondolin response buffering disabled for gateway ingress. If a request waits a long time before the first byte, tune zones[].gateway.ingress.upstreamHeaderTimeoutMs. If a long response can sit idle between body chunks, tune zones[].gateway.ingress.upstreamResponseTimeoutMs. Streaming responses are less sensitive to the body idle timeout when the model emits regular chunks.

Do not treat gateway.ingress timeout settings as a general "open ports" mechanism. Serving additional guest HTTP services, such as a Vite preview, local app server, or sidecar dashboard, requires explicit additional Gondolin ingress routes that map non-root path prefixes to guest ports. Route prefixes must not shadow Hermes root or /p/<profile>/... routes.

Raw TCP services are not HTTP ingress. Use configured tcpHosts for VM-to-host raw TCP mappings and keep HTTP serving on Gondolin ingress routes.
	`,
			),
		},
		{
			relativePath: 'docs/manual/mcp-portal.md',
			content: generatedPage(
				'MCP Portal',
				`
Managed Gateway Tool Portal, standalone Tool Portal, and standalone MCP Portal are separate operating surfaces. Managed Hermes exposes Tool Portal tools in the Gateway VM. External consumers may use explicitly configured standalone Tool Portal entrypoints or the separate mcp-portal mcp-proxy serve command.

Managed Gateway boot starts one common Tool Portal service process beside the Hermes framework process. The Hermes integration authenticates its native profile and uses one GatewayRuntimeClient over the private UDS. ToolPortalService owns policy, controller bindings, per-agent strict SSH, active uses, and Sandbox operations; Hermes never receives lease ids or SSH material.

	Tool Portal is the model-visible cross-backend contract layer for managed Hermes. It composes MCP providers, controller execution, and Tool VM runners behind one capability vocabulary. Its managed config pair is mcp.config.jsonc plus tool-portal.config.jsonc. Standalone Tool Portal uses tool-portal.config.jsonc with mode standalone and explicitly configured HTTP/MCP/stdio entrypoints. Standalone MCP Portal is a separate product that loads mcp.config.jsonc plus mcp-portal.config.jsonc. Managed Gateway does not load mcp-portal.config.jsonc or use standalone bearer/HMAC policy as managed authority, and it exposes no Tool Portal HTTP/MCP/stdio listener or public ingress.

		Agents should use progressive disclosure:
		1. tool_portal_list with requests[] for allowed capabilities and compact summaries.
		2. tool_portal_search with requests[] for discovery inside the scoped index.
		3. tool_portal_describe with requests[] for full JSON Schema and optional TypeScript/Zod helpers.
		4. tool_portal_call with calls[] to call authorized capabilities by namespace + name after seeing the schema.

	The Capability API above is distinct from the managed-only SSH Sandbox API. Capability calls select namespace + name and apply catalog, call, approval, and backend policy. Hermes BaseEnvironment uses GatewayRuntimeClient.sandbox for direct authenticated environment, shell, filesystem, process, stream, and terminal operations. Both paths may use the same current agent binding and service-owned SSH connection only after their distinct admission.

	All portal responses are { ok, items, diagnostics? }. Each item has id and status. Successful items use { status: "ok", value }; failed items use { status: "error", error }.

		For Managed Gateway, mcp.config.jsonc owns upstream MCP providers and tool-portal.config.jsonc owns agent assignments plus complete profiles. Profiles do not inherit from or merge with other profiles. Each profile declares namespaces, and every namespace must select an explicit backend.kind: mcp_provider, controller_execution, or tool_vm_runner. Each namespace carries tools.allow / tools.deny visibility selectors plus calls.withoutApproval and calls.requiresApproval call selectors. Namespaces absent from the profile are denied. The controller approval surface handles managed calls.requiresApproval; calls.withoutApproval permits direct managed calls. Any managed namespace that effectively admits a tool through calls.requiresApproval requires zone approvalAccess. Static validation and Gateway preflight fail closed when approvalAccess is absent; agent-vm does not infer a default. Denied tools do not enter the agent's catalog or search index.

		Namespace discovery uses only optional discovery.summary, bounded to 500 characters. MCP-backed namespaces author it once on the matching mcp.config.jsonc provider; do not duplicate it in Tool Portal policy. controller_execution and tool_vm_runner namespaces may author the same field on their Tool Portal namespace policy. Successful list/search/describe results return effective namespaceDiscovery separately from tool metadata. Managed Hermes renders admitted namespace name, availability, and optional summary once per session. configured_cli.safeHelp remains the per-operation capability description returned by discovery and is not namespace prompt text.

		approvalAccess.approvers entries are exactly kind: managed_gateway with approverId and no secret or credential. At most one managed_gateway authority may exist in a zone. Hermes presents managed approvals natively; Worker rejects managed approval authority. The controller exposes no external approval HTTP routes; Hermes API_SERVER_KEY authenticates the separate in-VM agent-message API.

		controller_execution operations are registered_action or configured_cli. Every configured_cli requires an invocation calls object: calls.deny and calls.requiresApproval match exact admitted command paths plus optional present flags, while calls.withoutApproval must be remaining_admitted. The fixed result order is deny > requires_approval > without_approval; rule order cannot weaken it. Keep commands[].flagRules only for allowed_values admission and put path-scoped flag denial in configured_cli.calls.deny. A visible configured_cli on the namespace direct baseline still requires zone approvalAccess when its calls.requiresApproval matcher list is non-empty; Hermes is the sole native presenter in this release.

		Configured CLI binds controller_host or a reusable credentialed ephemeral_managed_vm, never the leased Tool VM. Here ephemeral means controller-created, non-durable, and idle-retired; it does not mean one VM per RPC. The controller enforces one current credentialed VM per zone and authenticated agent; targets do not declare runtime ids. Each target declares exactly one file_binding or http_mediation credentialProjection. File bindings map agent-owned 1Password files into read-only memory paths. HTTP mediation gives the VM opaque placeholders while raw values remain host-side for exact hosts. Ordinary CLI config/state/cache remains on disposable COW. One agent runtime runs one command; concurrent calls return retryable busy and are never queued. Compatible calls reuse the VM until 15 idle minutes, but every call gets current policy and approval. imageReference remains a recipe path prepared at Gateway startup. Prepared image details, credential refs, file paths, and VM authority stay out of Gateway-safe projection. quick operations run for at most 5 seconds. open operations default to 120 seconds and accept a caller timeout up to 8 hours. tool_vm_runner remains direct Gateway-to-leased-Tool-VM strict SSH and does not send a per-command controller execution RPC.

		For immediate replacement of a value behind an unchanged secret ref, run agent-vm controller credential-runtime retire --zone <zone> --agent <agentId>. Without --force, an active runtime remains active. --force cancels its current command before exact cleanup. The command uses existing zone adminAccess and exposes no credential, VM, or lease identity.

		For standalone or external MCP Portal, mcp.config.jsonc owns upstream MCP providers and mcp-portal.config.jsonc owns agent assignments, complete MCP profiles, call policy, and optional external proxy authentication. Bearer credentials, HMAC approval tokens, credentialVersion, and externalAuth belong only to this standalone surface.

	Authored config is JSONC. $schema points at local config/schemas/*.schema.json files generated by agent-vm init. schemaVersion is the runtime compatibility gate.

	MCP JSON Schema is canonical for upstream MCP provider calls. Zod is derived for validation and helper code. Portal-neutral contracts used by Tool Portal and controller execution boundaries are Zod v4 schemas first, with JSON Schema generated from Zod for protocol surfaces. Invalid call arguments and schemas that cannot be converted return structured errors without calling upstream. Tool VMs can use the mcp-portal helper package but do not receive upstream MCP credentials.

	Prefer http-mediation for MCP provider API keys, including stdio providers, when the provider sends the env value in outbound HTTP headers or other Gondolin-supported request locations. The MCP server sees a placeholder env value; Gondolin swaps it for the real secret only for configured hosts. Use raw env injection only as an explicit exception for providers that cannot operate with placeholders.

	Store MCP provider secrets as raw values. Omit \`format\` when the upstream expects the raw value. Use \`format: { "kind": "bearer" }\` when an upstream expects Bearer presentation, or \`format: { "kind": "prefix", "prefix": "Token" }\` for provider-specific schemes. Prefix presentation inserts exactly one ASCII space between the prefix and the raw secret or mediated placeholder, and the prefix itself must not contain whitespace.

		Run agent-vm validate --mcp-live after editing managed MCP providers or Tool Portal profiles. Static validate checks the managed mcp.config.jsonc and tool-portal.config.jsonc schema and materialization. Live validate follows only active Tool Portal namespaces whose backend.kind is mcp_provider, starts their referenced MCP providers, runs tools/list, and reports provider namespace, transport, phase, and hints for failures. Providers configured in mcp.config.jsonc but not referenced by an active mcp_provider namespace are outside that validation run.

	Read-only/destructive annotations are trusted only for configured MCP-provider namespaces. Managed namespaces must be explicitly selected through calls.withoutApproval or calls.requiresApproval.
	Channel-native approval settings, such as Discord approver user IDs, remain deployment-owned.

	MCP provider URLs must use http or https. Loopback and private-network upstream URLs are allowed because authored config is trusted deployment config and sidecar/local MCP providers are a supported shape. Do not import untrusted MCP provider config directly; if config trust changes, add an explicit per-provider network allowlist before accepting private-network targets.

Credential redaction is not general PII filtering. Catalogs redact exact configured secrets only; outputs and errors also redact credential-shaped text. Treat upstream tool response content as agent-visible unless a deployment adds future response middleware policy.
`,
			),
		},
		{
			relativePath: 'docs/manual/agent-worker.md',
			content: generatedPage(
				'Agent Worker Gateway',
				`
Worker gateways run task VMs with explicit phases: plan, work, review, and wrapup.
Repo resources live under .agent-vm inside target repos and are refreshed with agent-vm resources update.
Worker repo edits happen under /work/repos/<repoId> inside the VM. The controller keeps host gitdirs separate for authenticated git operations.
`,
			),
		},
		{
			relativePath: 'docs/manual/secrets.md',
			content: generatedPage(
				'Secrets And Runtime Auth',
				`
Secrets are declared in ${options.systemConfigPath}.
Use http-mediation for service tokens that should be swapped into outbound requests by the controller.
Use env only when the gateway process itself must read the raw value.
Do not bake secrets into Dockerfiles or images.
For Tool VM-reaching mediated secrets, agentAccess is required and the zone must declare agents. Use agentAccess: "all" only for a deliberate all-declared-agents placeholder, or a non-empty agent list such as ["sun"] for per-agent delivery. The controller filters by agentId before resolving secret refs, so non-matching agents do not cause scoped refs to be read. For audience "both", agentAccess scopes Tool VM delivery only; gateway mediation remains zone-wide.

Zones scaffold controller SSH adminAccess as mode: "none" because secret-backed admin SSH requires an operator-created secret. To protect controller-mediated SSH, create the secret first, then change zones[].adminAccess to mode: "secret" with a real secret reference.
Use agent-vm controller ssh --zone <zoneId> for a protected Hermes gateway admin shell.
Hermes admin shells load HERMES_HOME, the Hermes CLI path, and Gondolin CA bundle variables without loading raw framework secrets. Run native commands such as hermes auth add <provider> inside that shell.
Controller SSH opens an interactive shell only. Do not use it as a one-shot command runner, and do not try to print raw SSH commands from the CLI.
Use agent-vm auth 1password <op-ref-or-url> --config ${options.systemConfigPath} to read a 1Password service-account token with op read and store it in the configured macOS Keychain service/account. Omit the ref/url only when pasting the token interactively.
Provider authentication is Hermes-native inside the protected interactive shell. Agent-vm has no provider-login or raw-secret compatibility command.
Tool VMs and agent sandboxes do not receive gateway SSH secrets.
`,
			),
		},
		{
			relativePath: 'docs/manual/tool-access.md',
			content: generatedPage(
				'Tool Access And Isolation',
				`
Hermes zones choose Tool VM images with defaultToolVmProfile and optional agentToolVmProfiles.

There are three isolation layers:

1. Auth-based isolation.
   The binary may exist for every agent, but only an agent's scoped sandbox contains credentials or seeded profile files. This is cheap, but the binary is still callable.

2. Tool Portal capability policy.
   Per-agent profiles can hide or deny named capabilities. This is useful, but it is not binary-level isolation if an admitted shell capability can still run arbitrary commands.

3. Per-zone Tool VM images.
   Use separate zones when binary-level differences must also carry gateway lifecycle, channel, or zone-files isolation.

Managed Hermes zones may declare multiple agents in zones[].agents. Use agentToolVmProfiles for per-agent Tool VM image selection inside the same zone, and use separate zones only when gateway lifecycle, channel, secret, or zone-files isolation matters more than sharing the gateway VM.
`,
			),
		},
		{
			relativePath: 'docs/manual/channels.md',
			content: generatedPage(
				'Gateway Channels',
				`
Discord is configured by the deployment, not by agent-vm defaults.

To add a channel:
1. Add non-secret native channel settings to the owning Hermes root or named profile config.yaml under the zone stateDir.
2. Add required secret sources and profile projections in ${options.systemConfigPath}.
3. Add egressHosts and any required websocketUpgrades entries for the channel endpoints.
4. Run agent-vm validate, then run agent-vm doctor after the deployment is ready.

Hermes Discord recipe:
- Add one distinct DISCORD_BOT_TOKEN source per declared agent and map it through gateway.profileSecretProjectionsByAgent.
- Add discord.com, *.discord.com, discord.gg, *.discord.gg, discord.media, *.discord.media, discordapp.com, *.discordapp.com, and *.discordapp.net to egressHosts with audience both.
- Add websocketUpgrades for Discord Gateway WebSockets: allow wss://gateway.discord.gg/ and wss://gateway-*.discord.gg/ for audience gateway.
- Do not add raw TCP entries for Discord Gateway WebSockets. Use native Gondolin WebSocket upgrades.
- Configure Hermes native Discord policy in the owning profile config.yaml. Do not put the token or other credential fields in native YAML.
- Do not add runtimeAuthHints to Hermes zones; they are Worker gateway runtime instructions only.
- Tool VM secrets must use injection http-mediation and declare agentAccess as "all" or a non-empty list of declared zone agent ids. source environment is allowed only as the controller-side source for mediated Tool VM secrets; never use injection env for Tool VM audience.

Managed Hermes profile secrets:
- Give every declared agent matching entries in gateway.profilesByAgent and gateway.profileSecretProjectionsByAgent.
- Map the API_SERVER_KEY target to one distinct injection env, audience gateway zone secret per agent. The separate root source named API_SERVER_KEY remains reserved and cannot be reused by a named profile.
- Map the DISCORD_BOT_TOKEN target to one distinct injection env, audience gateway zone secret per agent.
- Use each profile's own API key for /p/<profile>/... requests. Unprefixed root routes continue to use the root listener key.
- The only additional profile environment targets allowed for Hermes are DISCORD_ALLOW_BOTS and DISCORD_BOTS_REQUIRE_INLINE_MENTION; each source must use injection env and audience gateway.
- DISCORD_ALLOW_BOTS accepts none (safe default), mentions (only explicitly mentioned bot messages), or all. DISCORD_BOTS_REQUIRE_INLINE_MENTION=true adds a literal inline @mention gate for bot-authored messages.
- Map other profile credential targets to Gateway-reaching http-mediation sources; Hermes receives only their opaque placeholders.
- Agent VM writes complete target maps only to the exact memory-backed profiles/<profile>/.env files before stock Hermes starts.
- Keep common non-secret policy in the dedicated gateway.config config.yaml directory mounted read-only at /etc/hermes/config.yaml. HERMES_MANAGED_DIR remains unset; root/default and named profile homes remain direct stateDir RealFS.
- New named profiles receive native config.yaml with platforms.api_server.enabled: false because the default profile owns Hermes's single HTTP listener; the shared listener still authenticates /p/<profile>/ with that profile's API_SERVER_KEY. Existing named profile configs must contain the same explicit disable or Agent VM rejects them before boot instead of rewriting authored bytes.
- Durable root/profile .env and secret-bearing native Hermes config are rejected. Remove known legacy files explicitly; do not add migration or copy-back behavior.
- Do not configure Hermes profiles to reply to one another in a shared Discord channel. Upstream warns that reply pings can satisfy mention gates and create acknowledgement/feedback loops; any beta probe is bounded validation only, not a supported topology.
`,
			),
		},
		{
			relativePath: 'docs/manual/runtime-paths.md',
			content: generatedPage(
				'Runtime Paths',
				`
Managed Hermes Tool VMs run commands in rootfs/COW /work by default. /work is disposable execution space and is deleted with the Tool VM.
/workspace is the current agent's filtered durable RealFS workspace selected by the controller from stable agent identity. It is the only durable agent workspace exposed to that Tool VM.
/gitdirs/workspace.git is present only when the current agent enables zones[].agents[].workspaceGit. No parent Git directory or sibling agent Git database is exposed.
Managed Tool VMs do not currently expose a generic /agent-vm path. Worker task VMs retain their separately owned generated /agent-vm inputs.
/state is controller/gateway plumbing, not the primary place for agent docs.
worker repo edits live under /work/repos inside Worker gateway task VMs.
Worker gateway task VMs use /work/tmp for temporary files and /work/cache for disposable package-manager cache.
Hermes gateway VMs use /work/tmp and /work/cache for disposable runtime work; persistent zone files live at /zone and are backed by the derived zoneFilesDir. Hermes root native state lives directly under stateDir and named profile state lives under stateDir/profiles/<profileName>.

The Hermes adapter translates authenticated profile identity to the controller-authored agent projection. It never sends a Gateway path or host path as Tool VM storage authority.
Controller startup acquires <controllerRuntimeDir>/vm-ownership/controller-ownership.lock before secret resolution or VM reconciliation and holds it until shutdown completes. A second controller or offline cleanup process cannot enter destructive reconciliation while that lock is held.
The lock is mutual exclusion, not destruction evidence. The controller persists credentialed runtime records at controllerStateDir/zones/<zoneId>/credentialed-runtimes/<recordId>.json, schema-v2 Tool records at controllerStateDir/zones/<zoneId>/tool-leases/<recordId>.json, and the Gateway record at controllerStateDir/zones/<zoneId>/gateway-runtime.json. They bind controller or Gateway ownership to exact VM id, pid, and process-start identity cleanup evidence. Controller restart adopts no VM: it destroys verified credentialed and Tool runners before their Gateway, then starts a fresh tree. Unknown or mismatched identity preserves the record and refuses a successor. HTTP health and telemetry remain diagnostic only.

Per-agent workspace Git:
- Configure workspaceGit on the owning zones[].agents[] entry; absence disables Git.
- mode=local creates an isolated workspace Git database without a push capability.
- mode=remote creates the same isolated database and exposes the controller-owned workspace_git_push Tool Portal action for that agent.
- Tool VM Git SSH remains read-only: fetch is allowed and direct push is denied.
- The controller uses host-only HTTPS credentials, expected-head/CAS checks, and rejects a push to the configured default branch.
- Backups include durable workspace files and exclude zoneRuntimeDir Git metadata.
`,
			),
		},
		{
			relativePath: 'docs/manual/per-agent-setup.md',
			content: generatedPage(
				'Per-Agent Setup',
				`
Managed Hermes gateway zones may declare multiple agents. Every zones[].agents[] id must have one unique normalized gateway.profilesByAgent value and a matching gateway.profileSecretProjectionsByAgent entry. Agent-vm keys Tool VM lease identity by zone and agent id, never by profile path or session.

Per-agent secret isolation comes from distinct projected sources for API_SERVER_KEY and DISCORD_BOT_TOKEN plus controller-filtered http-mediation for other Gateway-reaching credentials. Agent-authored durable files belong under zoneFilesDir/agents/<agentId> and appear through the selected filtered /workspace projection; framework-private Hermes profile state remains in the Gateway and is not projected into Tool VMs.

Tool Portal profile policy is a capability layer. It does not remove binaries from the Tool VM image if an admitted shell capability can still run them.

Binary-level isolation requires different Tool VM images. Use agentToolVmProfiles for per-agent image differences inside one managed Hermes zone when gateway lifecycle can be shared. Use separate zones when the gateway VM, channel, secret, or zone-files boundary must also be separate.

Git workflow with zones[].agents[].workspaceGit:
- Agents may inspect, switch branches, merge, stage, and commit their own /workspace changes with normal Git commands.
- Do not run raw git push. Tool VM Git SSH is read-only and Tool VMs do not receive GitHub credentials.
- Remote mode exposes the controller-owned workspace_git_push Tool Portal action for the configured branch; local mode and absent workspaceGit expose no push action.
- The controller rejects the configured default branch. If it reports divergence, expected-head mismatch, or another rejection, stop and report the exact message.
`,
			),
		},
		{
			relativePath: 'docs/manual/troubleshooting.md',
			content: generatedPage(
				'Troubleshooting',
				`
Run agent-vm validate after config edits.
Run agent-vm doctor before starting or after changing images, secrets, or channel plugins.
Run agent-vm manual update after upgrading agent-vm to refresh this manual.

Hermes config rejection:
- config/gateways/<zone>/hermes-managed must contain only config.yaml.
- The managed config must declare complete plugins.enabled and plugins.disabled lists and keep agent-vm-tool-portal enabled.
- All admitted Hermes YAML rejects embedded credentials, native secrets, explicit Discord enablement, and extra port-binding platforms. Agent VM projects profile credentials separately.
- Named profile config must explicitly disable platforms.api_server.enabled because the root profile owns the shared listener.

Gateway not ready:
- Check agent-vm controller service-health for Hermes /health separately from the controller health snapshot.
- Check gateway-control-session before treating a Tool VM SSH failure as a framework outage.
- Check lease-heartbeat and lease-renew separately; an idle reusable lease and an active operation prove different paths.
- Check secret-resolution-failed as the current recovery blocker, not automatically as the original outage cause.
`,
			),
		},
	];
}
