export const GENERATED_MANUAL_MARKER = 'Generated by agent-vm manual. Do not edit by hand.';

export interface ManualTemplateOptions {
	readonly defaultZoneId: string;
	readonly systemConfigPath: string;
}

export interface ManualTemplateFile {
	readonly content: string;
	readonly relativePath: string;
}

function generatedPage(title: string, body: string): string {
	return `# ${GENERATED_MANUAL_MARKER}

# ${title}

${body.trim()}
`;
}

export function buildAgentVmAgentsTemplate(options: ManualTemplateOptions): string {
	return generatedPage(
		'Agent Instructions',
		`
This deployment uses agent-vm. Start with docs/manual/README.md, then drill into the specific manual page for the task.

Primary config:
- System config: ${options.systemConfigPath}
- Default zone: ${options.defaultZoneId}

Use docs/manual/layout.md before moving files or changing generated folders.
Use docs/manual/scope.md before changing OpenClaw sandbox scope or tool VM lease behavior.
Use docs/manual/tool-access.md before answering whether a tool binary, auth profile, or tool VM image should be agent-specific.
Use docs/manual/channels.md before helping a human configure Discord, Slack, Telegram, or another OpenClaw channel.
Use docs/manual/runtime-paths.md before answering where files appear inside VMs.
Use docs/manual/per-agent-setup.md before changing multi-agent layouts, scope=agent behavior, or per-agent tool/auth isolation.

Do not assume Discord is enabled by the framework. Channels and channel secrets are deployment-owned.
Do not silently edit privileged host/deployment config. Explain the proposed Dockerfile, secret, allowedHosts, websocketBypass, or OpenClaw config change and wait for the human to ask you to apply it.
`,
	);
}

export function buildManualTemplateFiles(
	_options: ManualTemplateOptions,
): readonly ManualTemplateFile[] {
	return [
		{
			relativePath: 'docs/manual/README.md',
			content: generatedPage(
				'agent-vm Deployment Manual',
				`
This manual is generated from the installed agent-vm package. It is the deployment-local guide for humans and coding agents.

Read in this order:
1. layout.md explains generated folders and ownership.
2. scope.md explains session, agent, and shared scope.
3. openclaw.md explains OpenClaw gateway configuration.
4. tool-access.md explains binary, auth, OpenClaw tool, and zone/image isolation.
5. channels.md explains how deployments add Discord or other channels.
6. runtime-paths.md explains /work and other in-VM paths.
7. per-agent-setup.md explains multi-agent scope and tool access choices.
8. migration-discord.md explains how existing Discord deployments keep working.
9. secrets.md explains runtime auth and HTTP mediation.

Local deployment notes belong in docs/manual/local-notes.md or another non-generated file.
`,
			),
		},
		{
			relativePath: 'docs/manual/layout.md',
			content: generatedPage(
				'Generated Layout',
				`
config/system.json is the controller config.
config/gateways/<zone>/openclaw.json is OpenClaw-owned gateway config.
vm-images/ contains deployment-owned Dockerfiles and Gondolin build configs.
stateDir stores durable gateway state.
zoneFilesDir stores durable user/workspace files for OpenClaw zones.
cacheDir stores rebuildable artifacts.
runtimeDir stores controller runtime artifacts that are not backup state.

OpenClaw Tool VMs mount the validated lease workspace at /work.
Worker task VMs keep repo files on rootfs/COW at /work/repos.
OpenClaw gateway VMs use /work/tmp and /work/cache for disposable runtime work.
Do not describe agent-vm Tool VM workspaces as /workspace.
`,
			),
		},
		{
			relativePath: 'docs/manual/scope.md',
			content: generatedPage(
				'Scope And Tool VM Reuse',
				`
OpenClaw sandbox scope decides which workspace a tool VM sees.

session scope isolates per conversation.
agent scope reuses a stable workspace for one agent identity.
shared scope intentionally shares one workspace across participants.

Tool VM lease identity follows scopeKey. TCP slots are capacity; they are not identity.

Example:
- shravan agent uses scope=agent and scopeKey=agent-shravan.
- alevtina agent uses scope=agent and scopeKey=agent-alevtina.
- Each agent gets its own scoped sandbox mounted at /work in its Tool VM.
- If both agents share one OpenClaw zone, they still share the zone's fallback toolProfile image.
- Use per-agent auth in the scoped sandbox for cheap isolation.
- Use separate zones or the final zone-fix per-agent tool-profile schema when binary-level tool isolation matters.
`,
			),
		},
		{
			relativePath: 'docs/manual/openclaw.md',
			content: generatedPage(
				'OpenClaw Gateway',
				`
Agent-vm provides VM lifecycle, storage mounts, TCP/HTTP mediation, image build, and tool VM leases.
OpenClaw owns plugin lifecycle, agents.list, channels, and gateway behavior.

The default scaffold enables Gondolin and memory-core support. It does not enable Discord.

Multi-zone controller work makes one controller process manage multiple typed zones. Until that schema lands, keep generated config examples conservative and use the current system.json reference for exact field names.
`,
			),
		},
		{
			relativePath: 'docs/manual/agent-worker.md',
			content: generatedPage(
				'Agent Worker Gateway',
				`
Worker gateways run task VMs with explicit phases: plan, work, review, and wrapup.
Repo resources live under .agent-vm inside target repos and are refreshed with agent-vm resources update.
Worker repo edits happen under /work/repos/<repoId> inside the VM. The controller keeps host gitdirs separate for authenticated git operations.
`,
			),
		},
		{
			relativePath: 'docs/manual/secrets.md',
			content: generatedPage(
				'Secrets And Runtime Auth',
				`
Secrets are declared in config/system.json.
Use http-mediation for service tokens that should be swapped into outbound requests by the controller.
Use env only when the gateway process itself must read the raw value.
Do not bake secrets into Dockerfiles or images.
`,
			),
		},
		{
			relativePath: 'docs/manual/tool-access.md',
			content: generatedPage(
				'Tool Access And Isolation',
				`
Today every agent in one OpenClaw zone uses the zone's configured toolProfile unless the installed agent-vm version documents per-agent tool-profile overrides.

There are three isolation layers:

1. Auth-based isolation.
   The binary may exist for every agent, but only an agent's scoped sandbox contains credentials. This works today and is cheap, but the binary is still callable.

2. OpenClaw tool allowlists.
   Per-agent tool policy can stop an agent from invoking certain named tools. This is useful, but it is not binary-level isolation if a broad shell tool can still run arbitrary commands.

3. Per-zone or per-agent tool VM images.
   This is binary-level isolation. Use separate zones today when agents need different installed binaries. Use the final zone-fix per-agent tool-profile schema after that work lands.

Use one OpenClaw zone when agents should share gateway resources and the same tool image is acceptable.
Use multiple zones when tool binary isolation, gateway lifecycle isolation, or per-agent image profiles matter more than memory cost.
`,
			),
		},
		{
			relativePath: 'docs/manual/channels.md',
			content: generatedPage(
				'OpenClaw Channels',
				`
Discord is configured by the deployment, not by agent-vm defaults.

To add a channel:
1. Install or bake the plugin in the deployment Dockerfile if needed.
2. Add the plugin to plugins.allow in openclaw.json.
3. Add plugin or channels config in openclaw.json.
4. Add required secrets in config/system.json.
5. Add allowedHosts and websocketBypass entries for the channel endpoints.
6. Rebuild the gateway image and run agent-vm doctor.

Discord recipe:
- Add DISCORD_BOT_TOKEN as a zone secret.
- Add discord.com and cdn.discordapp.com to allowedHosts.
- Add gateway.discord.gg:443 to websocketBypass.
- Enable channels.discord or the Discord plugin entry in deployment-owned openclaw.json.
- Bake any required Discord plugin/runtime dependencies in the deployment Dockerfile.
- Add runtimeAuthHints only if the agent should know that a Discord service token exists.
`,
			),
		},
		{
			relativePath: 'docs/manual/runtime-paths.md',
			content: generatedPage(
				'Runtime Paths',
				`
OpenClaw Tool VMs run commands in /work.
/work is the validated, scope-selected workspaceDir from the OpenClaw lease request.
/agent-vm contains generated agent-vm runtime instructions.
/state is controller/gateway plumbing, not the primary place for agent docs.
worker repo edits live under /work/repos inside Worker gateway task VMs.
Worker gateway task VMs use /work/tmp for temporary files and /work/cache for disposable package-manager cache.
OpenClaw gateway VMs use /work/tmp and /work/cache for disposable runtime work; persistent zone files live at the configured zoneFilesDir path.

Do not use /workspace in new docs, prompts, or examples for agent-vm Tool VMs.
`,
			),
		},
		{
			relativePath: 'docs/manual/per-agent-setup.md',
			content: generatedPage(
				'Per-Agent Setup',
				`
A single OpenClaw gateway can host multiple agents. Use scope=agent when each agent should have a stable workspace and reusable Tool VM lease identity.

Per-agent auth isolation works today by placing credentials in the agent's scoped sandbox. The same tool binary can exist for every agent, but only the intended agent's /work contains usable credentials.

OpenClaw tool allowlists are a policy layer. They do not remove binaries from the Tool VM image if a broad shell tool can still run them.

Binary-level isolation requires different Tool VM images. Today that means separate zones with different toolProfiles, or the final per-agent tool-profile schema after the multi-zone work lands.
`,
			),
		},
		{
			relativePath: 'docs/manual/migration-discord.md',
			content: generatedPage(
				'Discord Migration',
				`
Agent-vm defaults are channel-neutral. Existing Discord deployments keep Discord by owning the deployment layer:

1. Keep Discord plugin/runtime installation in the deployment Dockerfile.
2. Keep Discord enabled in config/gateways/<zone>/openclaw.json.
3. Keep DISCORD_BOT_TOKEN in config/system.json zone secrets.
4. Keep discord.com and cdn.discordapp.com in allowedHosts.
5. Keep gateway.discord.gg:443 in websocketBypass.

Do not reintroduce Discord into agent-vm init defaults. Use this page as the deployment recipe.
`,
			),
		},
		{
			relativePath: 'docs/manual/troubleshooting.md',
			content: generatedPage(
				'Troubleshooting',
				`
Run agent-vm validate after config edits.
Run agent-vm doctor before starting or after changing images, secrets, or channel plugins.
Run agent-vm manual update after upgrading agent-vm to refresh this manual.
`,
			),
		},
	];
}
