import fs from 'node:fs';

export const GENERATED_MARKER = 'Generated by agent-vm resources. Do not edit by hand.';

const CONTRACT_TYPE_SOURCE_CANDIDATES = [
	'../config/resource-contracts/repo-resource-contract-types.d.ts',
	'../config/resource-contracts/repo-resource-contract-types.ts',
] as const;

function readRepoResourceContractTypeSource(): string {
	for (const relativePath of CONTRACT_TYPE_SOURCE_CANDIDATES) {
		try {
			return fs.readFileSync(new URL(relativePath, import.meta.url), 'utf8');
		} catch (error) {
			if (
				typeof error === 'object' &&
				error !== null &&
				'code' in error &&
				error.code === 'ENOENT'
			) {
				continue;
			}
			throw error;
		}
	}
	throw new Error('Unable to locate repo resource contract type declarations.');
}

function buildAmbientRepoResourceContractDeclarations(): string {
	const declarations = readRepoResourceContractTypeSource()
		.replace(/^export\s+(interface|type)\s+/gmu, '$1 ')
		.replace(/^\s*export\s*\{\s*\};?\s*$/gmu, '')
		.replace(/^\/\/# sourceMappingURL=.*$/gmu, '')
		.trim();
	const indentedDeclarations = declarations
		.split('\n')
		.map((line) => (line.length === 0 ? line : `\t${line}`))
		.join('\n');
	return `export {};

declare global {
${indentedDeclarations}
}
`;
}

export function buildRepoResourcesTemplate(): string {
	return `/// <reference path="./repo-resources.d.ts" />

export function describeRepoResources(): RepoResourcesDescription {
\treturn {
\t\trequires: {},
\t\tprovides: {},
\t};
}

export async function finalizeRepoResourceSetup(
\t_input: FinalizeRepoResourceSetupInput,
): Promise<RepoResourcesFinal> {
\treturn {
\t\tresources: {},
\t\tgenerated: [],
\t};
}
`;
}

export function buildRepoResourcesDeclarationTemplate(): string {
	return `// ${GENERATED_MARKER}

${buildAmbientRepoResourceContractDeclarations()}`;
}

export function buildRunSetupShellTemplate(): string {
	return `#!/usr/bin/env bash
set -euo pipefail

# This script is repo-owned imperative bootstrap. agent-vm calls it once for
# every requested repo after any selected Compose services for that repo are
# running.
#
# Inputs:
#   COMPOSE_PROJECT_NAME: Docker Compose project created by the controller.
#   RESOURCE_OUTPUT_DIR: Directory for generated mocks, fixtures, and logs.
#
# This script does not receive resource names or resolved host/port values.
# Put schema-shaped final env and binding logic in finalizeRepoResourceSetup().
compose_project_name="\${COMPOSE_PROJECT_NAME:?COMPOSE_PROJECT_NAME is required}"
output_dir="\${RESOURCE_OUTPUT_DIR:?RESOURCE_OUTPUT_DIR is required}"

mkdir -p "$output_dir/unstructured"

# Example:
# docker compose -p "$compose_project_name" exec pg psql -U app -d app -f seed.sql
`;
}

export function buildDockerComposeTemplate(): string {
	return `services: {}\n`;
}

export function buildRepoResourcesAgentsTemplate(): string {
	return `# ${GENERATED_MARKER}

# Repo Resources

This directory is the repo-resource contract for agent-vm. Keep the mental model intact when editing it:

- Install or refresh the CLI with pnpm -g install @agent-vm/agent-vm before running repo resource commands locally.
- repo-resources.ts is the contract the controller loads and validates. It declares what this repo requires, what it can provide, and how final resources are exposed to the VM.
- repo-resources.d.ts, AGENTS.md, and README.md are generated. Run agent-vm resources update after agent-vm changes, and do not hand-edit those generated files.
- run-setup.sh and docker-compose.yml are provider bootstrap files. They can do whatever this repo needs after selected Compose services are running, but they are not the schema contract.
- Put schema-shaped logic in TypeScript: compute final env from input.selectedResources, return generated paths, and report anything the controller should validate.
- Put repo bootstrap in run-setup.sh: psql seeding, volume prep, temp fixture generation, and external binaries. run-setup.sh is called once per requested repo. run-setup.sh receives COMPOSE_PROJECT_NAME plus RESOURCE_OUTPUT_DIR.
- Put services in docker-compose.yml. Do not publish host ports with ports:; use internal service ports because multiple repos and tasks run in parallel.
- Do not use resources-post-hook.ts, setup-repo-resources.sh, or legacy .agent-vm resource files.
`;
}

export function buildRepoResourcesReadmeTemplate(): string {
	return `# ${GENERATED_MARKER}

# .agent-vm resources

## Local CLI

Install or refresh the agent-vm CLI before running resource commands locally:

\`\`\`bash
pnpm -g install @agent-vm/agent-vm
\`\`\`

Use agent-vm resources validate after editing repo-resources.ts, run-setup.sh, or docker-compose.yml. Use agent-vm resources update after upgrading agent-vm to refresh only generated docs and type declarations.

## System model

repo-resources.ts is the contract the controller actually speaks to. The controller loads it, validates its return values, decides which logical resources are selected, starts selected Compose providers, runs repo setup, and then calls finalizeRepoResourceSetup(input).

run-setup.sh and docker-compose.yml are implementation details for repo bootstrap. Shell setup runs once for every requested repo; Compose startup only happens for services selected to provide logical resources. These files can seed a database, prepare files, run brittle external binaries, or start repo-local services, but they do not define the controller-facing schema.

The split is intentional:

- TypeScript is declarative and schema-shaped. Use repo-resources.ts to declare requirements/providers, compute final env from input.selectedResources, and return generated paths the controller should validate.
- Shell is imperative bootstrap. Use run-setup.sh for repo setup work that is easier or more natural in shell.
- Compose owns services. Use docker-compose.yml for repo-local providers and do not publish host ports.

## Runtime flow

1. describeRepoResources() returns the partial contract: required logical resources and providers this repo can offer.
2. If this repo is selected to provide resources, the controller starts all selected Compose services for this repo in one Compose project.
3. The controller runs run-setup.sh once for every requested repo with COMPOSE_PROJECT_NAME and RESOURCE_OUTPUT_DIR set.
4. The controller calls finalizeRepoResourceSetup(input). This is where repo-resources.ts receives resolved binding and target information.
5. finalizeRepoResourceSetup(input) returns final env and generated file declarations for the VM.

run-setup.sh is called once per requested repo. It receives COMPOSE_PROJECT_NAME and RESOURCE_OUTPUT_DIR. It does not receive resource names or resolved target.host/target.port. If you need resolved host/port values, use finalizeRepoResourceSetup(input) and input.selectedResources.

Generated mocks and fixtures should live under RESOURCE_OUTPUT_DIR/unstructured. Any generated paths returned from finalizeRepoResourceSetup(input) must stay inside RESOURCE_OUTPUT_DIR.

## Compose rules

docker-compose.yml services are started under a controller-owned Compose project name. Do not publish host ports with ports:, because parallel repos and tasks can collide. Use internal service ports and let the controller inject tcpHosts.

## Generated files

agent-vm resources update rewrites only repo-resources.d.ts, AGENTS.md, and README.md. It does not touch repo-resources.ts, run-setup.sh, or docker-compose.yml after initial generation.
`;
}
