"""Typed managed Tool Portal cache, inventory, and orientation primitives."""

from .cache import (
    CacheClosedError,
    CacheSnapshot,
    CacheTransitionError,
    MarkAlreadyPresent,
    MarkClosed,
    MarkIfAbsentResult,
    MarkInserted,
    PluginStateCache,
    PopulationAlreadyStarted,
    PopulationStarted,
    PublicationResult,
    TransitionResult,
)
from .models import (
    EvictedState,
    EvictionReason,
    EvictionRecord,
    ExhaustedState,
    InjectionCacheKey,
    InjectionMarker,
    InventoryCacheKey,
    InventoryReadyValue,
    NamespaceAvailability,
    NamespaceInventory,
    OrientationRenderFailure,
    PopulatingState,
    PopulationFailureClass,
    PopulationHandle,
    ReadyState,
    RenderedOrientation,
    UnresolvedState,
)
from .renderer import (
    MAX_DISPLAYED_NAMESPACE_COUNT,
    MAX_ORIENTATION_UTF8_BYTES,
    render_orientation,
)

__all__ = (
    "CacheClosedError",
    "CacheSnapshot",
    "CacheTransitionError",
    "EvictedState",
    "EvictionReason",
    "EvictionRecord",
    "ExhaustedState",
    "InventoryCacheKey",
    "InventoryReadyValue",
    "InjectionCacheKey",
    "InjectionMarker",
    "MarkAlreadyPresent",
    "MarkClosed",
    "MarkIfAbsentResult",
    "MarkInserted",
    "MAX_DISPLAYED_NAMESPACE_COUNT",
    "MAX_ORIENTATION_UTF8_BYTES",
    "NamespaceAvailability",
    "NamespaceInventory",
    "OrientationRenderFailure",
    "PluginStateCache",
    "PopulationAlreadyStarted",
    "PopulationFailureClass",
    "PopulationHandle",
    "PopulationStarted",
    "PopulatingState",
    "PublicationResult",
    "ReadyState",
    "RenderedOrientation",
    "TransitionResult",
    "UnresolvedState",
    "render_orientation",
)
