import { createHash } from 'node:crypto';

import { portalToolRecordSchema, type PortalToolRecord } from '../catalog-types.js';
import { encodeToolRef } from '../tool-ref.js';

export interface CatalogArtifactInput {
	readonly tools: readonly PortalToolRecord[];
}

function toIdentifierPart(value: string): string {
	const words = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
	if (words.length === 0) {
		return 'tool';
	}

	return words.map((word) => word.slice(0, 1).toUpperCase() + word.slice(1)).join('');
}

function shortToolRefHash(toolRef: string): string {
	return createHash('sha256').update(toolRef).digest('hex').slice(0, 8);
}

function toToolConstantName(tool: PortalToolRecord & { readonly toolRef: string }): string {
	const namespacePart = toIdentifierPart(tool.namespace);
	const toolNamePart = toIdentifierPart(tool.toolName);
	const identifier = `${namespacePart}${toolNamePart}${shortToolRefHash(tool.toolRef)}Tool`;

	return identifier.slice(0, 1).toLowerCase() + identifier.slice(1);
}

export function generateTypescriptCatalogArtifact(input: CatalogArtifactInput): string {
	const tools = input.tools
		.map((tool) => portalToolRecordSchema.parse(tool))
		.toSorted((left, right) => {
			const leftRef = encodeToolRef({ namespace: left.namespace, toolName: left.toolName });
			const rightRef = encodeToolRef({ namespace: right.namespace, toolName: right.toolName });
			return leftRef.localeCompare(rightRef);
		});

	const catalogEntries = tools.map((tool) =>
		Object.assign({}, tool, {
			toolRef: encodeToolRef({ namespace: tool.namespace, toolName: tool.toolName }),
		}),
	);
	const constants = catalogEntries
		.map((tool) => {
			const constantName = toToolConstantName(tool);
			return `export const ${constantName} = requireCatalogTool(${JSON.stringify(tool.toolRef)});`;
		})
		.join('\n');

	return [
		'// Generated by agent-vm-mcp-portal. JSON Schema is canonical; Zod is derived for runtime validation.',
		"import * as z from 'zod';",
		'',
		`export const portalCatalog = ${JSON.stringify({ tools: catalogEntries }, null, '\t')} as const;`,
		'',
		constants,
		'',
		'function requireCatalogTool(toolRef: string): (typeof portalCatalog.tools)[number] {',
		'\tconst tool = portalCatalog.tools.find((catalogTool) => catalogTool.toolRef === toolRef);',
		'\tif (!tool) {',
		'\t\tthrow new Error(`Unknown MCP portal toolRef: ${toolRef}`);',
		'\t}',
		'\treturn tool;',
		'}',
		'',
		'export function createInputValidator(toolRef: string): z.ZodType {',
		'\tconst tool = requireCatalogTool(toolRef);',
		'\treturn z.fromJSONSchema(tool.inputSchema);',
		'}',
		'',
	].join('\n');
}
