import type {
	ExternalResources,
	ResolvedRepoResourcesFinal,
} from '../config/resource-contracts/index.js';
import type { SystemConfig } from '../config/system-config.js';

type RuntimeAuthHint = NonNullable<SystemConfig['zones'][number]['runtimeAuthHints']>[number];

export interface ResolvedRuntimeResource {
	readonly name: string;
	readonly host: string;
	readonly port: number;
	readonly envVars: readonly string[];
	readonly outputPath?: string | undefined;
}

export interface RepoResourceFinalizationSummary {
	readonly final: ResolvedRepoResourcesFinal;
	readonly outputDir: string;
	readonly repoId: string;
}

export interface BuildResolvedRuntimeResourcesOptions {
	readonly externalResources: ExternalResources;
	readonly repoFinalizations: readonly RepoResourceFinalizationSummary[];
}

export interface BuildRuntimeInstructionsOptions {
	readonly resolvedResources: readonly ResolvedRuntimeResource[];
	readonly runtimeAuthHints: readonly RuntimeAuthHint[];
	readonly taskId: string;
	readonly workspaceDir: string;
}

export interface BuiltRuntimeInstructions {
	readonly runtimeInstructions: string;
	readonly workspaceAgentsMd: string;
	readonly agentRuntimeFiles: Readonly<Record<string, string>>;
}

function buildWorkspaceSection(options: BuildRuntimeInstructionsOptions): string {
	return [
		'## Workspace',
		`- Task id: ${options.taskId}`,
		`- Workspace root: ${options.workspaceDir}`,
		'- Workspace agent index: /workspace/AGENTS.md',
		'- Runtime agent index: /agent-vm/agents.md',
		'- Requested repositories are cloned under the workspace root. Use the task prompt and workspace contents for repo-specific work.',
	].join('\n');
}

function formatResourceLines(resources: readonly ResolvedRuntimeResource[]): readonly string[] {
	if (resources.length === 0) {
		return ['- No resolved repo or external resources were generated for this task.'];
	}
	return resources.flatMap((resource) => [
		`- ${resource.name}: ${resource.host}:${String(resource.port)}`,
		`  Env vars: ${resource.envVars.length ? resource.envVars.join(', ') : '(none)'}`,
		...(resource.outputPath ? [`  Output: ${resource.outputPath}`] : []),
	]);
}

function buildResourcesSection(options: BuildRuntimeInstructionsOptions): string {
	return [
		'## Resources',
		'- Resolved resource facts are generated by the controller. Use env var names and VM-visible host bindings below; do not inspect /state for resource configuration.',
		...formatResourceLines(options.resolvedResources),
	].join('\n');
}

function buildControllerToolsSection(): string {
	return [
		'## Controller tools',
		'- Use git-push to push agent branches. Do not run git push directly.',
		'- Use git-pull-default to update protected/default branches.',
	].join('\n');
}

type RuntimeAuthRecipeBuilder = (hint: RuntimeAuthHint) => readonly string[];

function formatAuthHintHeading(hint: RuntimeAuthHint): string {
	return `### ${hint.secret} - service ${hint.service} - hosts ${hint.hosts.join(', ')}`;
}

function formatAuthHintTools(hint: RuntimeAuthHint): string {
	const tools = hint.tools.length ? hint.tools.join(', ') : '(none declared)';
	return `Tools: ${tools}`;
}

function formatLiteralEnvPlaceholder(secretName: string): string {
	return `\${${secretName}}`;
}

function buildNpmAuthRecipe(hint: RuntimeAuthHint): readonly string[] {
	const registryHost = hint.hosts[0] ?? 'registry.npmjs.org';
	const literalPlaceholder = formatLiteralEnvPlaceholder(hint.secret);
	return [
		'Before any npm, pnpm, yarn install/add/publish command, write the npm user config:',
		'',
		`  printf '//${registryHost}/:_authToken=${literalPlaceholder}\\n' > "$HOME/.npmrc"`,
		'',
		'Use >, not >>. This setup is safe to re-run because it overwrites the generated auth line.',
		'The single quotes are required: npm substitutes the env placeholder at registry-call time. Double quotes would expand the placeholder into the file and break mediation.',
		'npm, pnpm, and yarn-classic read "$HOME/.npmrc".',
		'If you must use yarn-berry, configure the registry in .yarnrc.yml instead:',
		'',
		'  npmRegistries:',
		`    "//${registryHost}":`,
		`      npmAuthToken: "${literalPlaceholder}"`,
	];
}

function buildGithubAuthRecipe(hint: RuntimeAuthHint): readonly string[] {
	return [
		'Before any gh command, copy the mediated placeholder into GH_TOKEN for that command:',
		'',
		`  GH_TOKEN="$${hint.secret}" gh pr create --base <default> --title "..." --body "..."`,
		'',
		'gh refuses authenticated API operations unless GH_TOKEN is set. The proxy substitutes the real token at the wire level for the listed hosts.',
		'Do not run raw git push. Use the git-push controller tool.',
	];
}

function buildPythonPackageIndexAuthRecipe(hint: RuntimeAuthHint): readonly string[] {
	const indexHost = hint.hosts[0] ?? '<private-python-index-host>';
	return [
		'Before any uv command that uses this private Python package index, configure uv to read the mediated placeholder.',
		'',
		'Prefer an explicit index URL scoped to the uv command:',
		'',
		`  UV_INDEX_URL="https://__token__:$${hint.secret}@${indexHost}/simple" uv pip install <package-or-requirements>`,
		'',
		'Keep the env placeholder literal until uv makes the outbound request to the listed host.',
	];
}

const authRecipes: Readonly<Record<string, RuntimeAuthRecipeBuilder>> = {
	github: buildGithubAuthRecipe,
	npm: buildNpmAuthRecipe,
	pypi: buildPythonPackageIndexAuthRecipe,
	'pypi-private': buildPythonPackageIndexAuthRecipe,
	python: buildPythonPackageIndexAuthRecipe,
	'python-package-index': buildPythonPackageIndexAuthRecipe,
};

function buildUnknownAuthRecipe(hint: RuntimeAuthHint): readonly string[] {
	return [
		`Before using these tools, you MUST configure your toolchain to read the placeholder env var $${hint.secret}.`,
		'Do not work around the proxy, do not inline token values, and do not skip validation.',
		'If you do not know the correct setup for this service, report an infrastructure/auth setup gap with the exact command you were trying to run.',
	];
}

function buildAuthHintBlock(hint: RuntimeAuthHint): readonly string[] {
	const recipeBuilder = authRecipes[hint.service.toLowerCase()] ?? buildUnknownAuthRecipe;
	return [formatAuthHintHeading(hint), formatAuthHintTools(hint), '', ...recipeBuilder(hint)];
}

function buildAuthSection(options: BuildRuntimeInstructionsOptions): string {
	const hintBlocks = options.runtimeAuthHints.flatMap((hint) => ['', ...buildAuthHintBlock(hint)]);
	if (hintBlocks.length === 0) {
		return [
			'## Mediated auth',
			'- No runtime auth hints were declared for this task.',
			'- If auth blocks validation, report an infrastructure/auth setup failure with the exact failing command and error.',
		].join('\n');
	}
	return [
		'## Mediated auth',
		'The env vars below are mediation placeholders. The proxy substitutes the real secret only on outbound calls to the listed hosts. You MUST keep the literal placeholder string. Never print, log, copy, inspect, or inline it.',
		'',
		'You MUST configure each tool below before running any command that uses it. If a configured command still returns 401, 403, or 404 on the listed hosts, that is an infrastructure/auth setup failure: stop, report the exact failing command and output, do not skip validation, and do not edit product code to work around auth.',
		...hintBlocks,
	].join('\n');
}

function buildRuntimeSurfaceSection(): string {
	return [
		'## Runtime files',
		'- /workspace/AGENTS.md points to /agent-vm/agents.md.',
		'- /workspace/CLAUDE.md is a symlink to /workspace/AGENTS.md.',
		'- /agent-vm/agents.md is the agent-facing index for generated runtime facts.',
		'- /agent-vm/CLAUDE.md is a symlink to /agent-vm/agents.md.',
		'- /agent-vm/runtime-instructions.md contains this same generated runtime instruction content.',
		'- /state exists in the VM, but it is worker/controller plumbing. Do not treat /state as the primary agent documentation surface.',
	].join('\n');
}

function buildAgentRuntimeFiles(
	options: BuildRuntimeInstructionsOptions,
	runtimeInstructions: string,
): Readonly<Record<string, string>> {
	return {
		'agents.md': [
			'# Agent VM runtime',
			'Read this generated file before making assumptions about this task runtime.',
			'Read /agent-vm/runtime-instructions.md for generated runtime facts.',
			'',
			'## Resources',
			...formatResourceLines(options.resolvedResources),
		].join('\n'),
		'runtime-instructions.md': runtimeInstructions,
	};
}

export function buildResolvedRuntimeResources(
	options: BuildResolvedRuntimeResourcesOptions,
): readonly ResolvedRuntimeResource[] {
	return [
		...Object.entries(options.externalResources).map(([name, resource]) => ({
			name,
			host: resource.binding.host,
			port: resource.binding.port,
			envVars: Object.keys(resource.env).toSorted(),
		})),
		...options.repoFinalizations.flatMap((finalization) =>
			Object.entries(finalization.final.resources).map(([name, resource]) => ({
				name,
				host: resource.binding.host,
				port: resource.binding.port,
				envVars: Object.keys(resource.env).toSorted(),
				outputPath: `/agent-vm/resources/${finalization.repoId}`,
			})),
		),
	];
}

export function buildRuntimeInstructions(
	options: BuildRuntimeInstructionsOptions,
): BuiltRuntimeInstructions {
	const runtimeInstructions = [
		'# Runtime instructions',
		buildWorkspaceSection(options),
		buildRuntimeSurfaceSection(),
		buildResourcesSection(options),
		buildControllerToolsSection(),
		buildAuthSection(options),
	].join('\n\n');
	return {
		runtimeInstructions,
		workspaceAgentsMd:
			'# Workspace agent index\n\nStart with /agent-vm/agents.md for generated runtime facts.\n',
		agentRuntimeFiles: buildAgentRuntimeFiles(options, runtimeInstructions),
	};
}
