export const GATEWAY_CONTROL_CALLER_CONTEXT_PROOF_KEY_ENV =
	'AGENT_VM_GATEWAY_CONTROL_CALLER_CONTEXT_PROOF_KEY';

export const GATEWAY_CONTROL_PRIVATE_ENVIRONMENT_NAMES = [
	GATEWAY_CONTROL_CALLER_CONTEXT_PROOF_KEY_ENV,
] as const;

export type GatewayControlPrivateEnvironmentName =
	(typeof GATEWAY_CONTROL_PRIVATE_ENVIRONMENT_NAMES)[number];
