import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { execa } from 'execa';
import { describe, expect, it } from 'vitest';

const repoRoot = process.cwd();
const agentVmCliPath = path.join(
	repoRoot,
	'packages',
	'agent-vm',
	'dist',
	'cli',
	'agent-vm-entrypoint.js',
);

async function readText(targetDir: string, relativePath: string): Promise<string> {
	return await fs.readFile(path.join(targetDir, relativePath), 'utf8');
}

async function updateGeneratedManual(targetDir: string): Promise<void> {
	await execa(
		'node',
		[
			agentVmCliPath,
			'manual',
			'update',
			'--agents',
			'--default-zone',
			'shravan',
			'--target-dir',
			targetDir,
		],
		{ reject: true, timeout: 30_000 },
	);
}

async function readGeneratedManualSnapshot(
	targetDir: string,
): Promise<Readonly<Record<string, string>>> {
	const manualDirectory = path.join(targetDir, 'docs', 'manual');
	const manualFileNames = (await fs.readdir(manualDirectory)).toSorted();
	return Object.fromEntries(
		await Promise.all(
			manualFileNames.map(async (manualFileName) => [
				manualFileName,
				await fs.readFile(path.join(manualDirectory, manualFileName), 'utf8'),
			]),
		),
	);
}

describe('smoke: agent-vm manual CLI', () => {
	it('updates generated manual files from the built CLI', async () => {
		const targetDir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-vm-manual-cli-'));

		await updateGeneratedManual(targetDir);

		expect(await readText(targetDir, 'docs/manual/README.md')).toContain(
			'Generated by agent-vm manual',
		);
		const runtimePaths = await readText(targetDir, 'docs/manual/runtime-paths.md');
		expect(runtimePaths).toContain('run commands in rootfs/COW /work by default');
		expect(runtimePaths).toContain("/workspace is the current agent's filtered durable RealFS");
		expect(runtimePaths).toContain('/gitdirs/workspace.git is present only when');
		expect(runtimePaths).toContain('controller-owned workspace_git_push Tool Portal action');
		expect(runtimePaths).not.toContain('gateway.zoneGit');
		expect(runtimePaths).not.toContain('/scratch');
		const toolVmLeases = await readText(targetDir, 'docs/manual/tool-vm-leases.md');
		expect(toolVmLeases).toContain(
			'sends typed requests to the common Tool Portal service over the private UDS',
		);
		expect(toolVmLeases).toContain(
			'common Tool Portal service owns current-epoch agent bindings, per-agent strict SSH connections',
		);
		expect(toolVmLeases).toContain('old lease id is correlation only, not authority');
		expect(toolVmLeases).toContain('No later shell, file, exec, heartbeat, or finalize work');
		const operationsManual = await readText(targetDir, 'docs/manual/operations.md');
		expect(operationsManual).toContain('controller_final');
		expect(operationsManual).toContain('stale_to_reacquired');
		const observabilityManual = await readText(targetDir, 'docs/manual/observability.md');
		expect(observabilityManual).toContain(
			'Per-zone observability supports managed Hermes gateways through Gondolin HTTP mediation.',
		);
		expect(observabilityManual).toContain('zones[].observability.services');
		expect(observabilityManual).toContain('agent-vm-tool-portal');
		expect(observabilityManual).toContain(
			'Tool VM SSH is the only managed gateway raw TCP exception.',
		);
		expect(observabilityManual).not.toContain(
			'observability is disabled during the Socket.IO control-plane hard cutover',
		);
		expect(await readText(targetDir, 'docs/manual/layout.md')).toContain('config/system.jsonc');
		expect(await readText(targetDir, 'AGENTS.md')).toContain('shravan');
		expect(await readText(targetDir, 'AGENTS.md')).toContain('config/system.jsonc');
		expect(await fs.readlink(path.join(targetDir, 'CLAUDE.md'))).toBe('AGENTS.md');

		const firstManualSnapshot = await readGeneratedManualSnapshot(targetDir);
		await updateGeneratedManual(targetDir);
		expect(await readGeneratedManualSnapshot(targetDir)).toEqual(firstManualSnapshot);
	});
});
