import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { execa } from 'execa';
import { describe, expect, it } from 'vitest';

const repoRoot = process.cwd();
const agentVmCliPath = path.join(
	repoRoot,
	'packages',
	'agent-vm',
	'dist',
	'cli',
	'agent-vm-entrypoint.js',
);

async function readText(targetDir: string, relativePath: string): Promise<string> {
	return await fs.readFile(path.join(targetDir, relativePath), 'utf8');
}

describe('smoke: agent-vm manual CLI', () => {
	it('updates generated manual files from the built CLI', async () => {
		const targetDir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-vm-manual-cli-'));

		await execa(
			'node',
			[
				agentVmCliPath,
				'manual',
				'update',
				'--agents',
				'--default-zone',
				'shravan',
				'--target-dir',
				targetDir,
			],
			{ reject: true, timeout: 30_000 },
		);

		expect(await readText(targetDir, 'docs/manual/README.md')).toContain(
			'Generated by agent-vm manual',
		);
		expect(await readText(targetDir, 'docs/manual/runtime-paths.md')).toContain(
			'OpenClaw Tool VMs run commands in /work',
		);
		expect(await readText(targetDir, 'AGENTS.md')).toContain('shravan');
		expect(await fs.readlink(path.join(targetDir, 'CLAUDE.md'))).toBe('AGENTS.md');
	});
});
