import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { execa } from 'execa';
import { describe, expect, it } from 'vitest';

const repoRoot = process.cwd();
const agentVmCliPath = path.join(
	repoRoot,
	'packages',
	'agent-vm',
	'dist',
	'cli',
	'agent-vm-entrypoint.js',
);

const expectedResourceFiles = [
	'.agent-vm/repo-resources.ts',
	'.agent-vm/repo-resources.d.ts',
	'.agent-vm/run-setup.sh',
	'.agent-vm/docker-compose.yml',
	'.agent-vm/AGENTS.md',
	'.agent-vm/README.md',
] as const;

async function readResourceFile(targetDir: string, relativePath: string): Promise<string> {
	return await fs.readFile(path.join(targetDir, relativePath), 'utf8');
}

async function runAgentVmResourcesCommand(
	targetDir: string,
	command: 'init' | 'update' | 'validate',
): Promise<void> {
	await execa('node', [agentVmCliPath, 'resources', command], {
		cwd: targetDir,
		reject: true,
		timeout: 30_000,
	});
}

describe('smoke: agent-vm resources CLI', () => {
	it('creates, validates, and updates repo resource files without clobbering user-owned files', async () => {
		const targetDir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-vm-resources-cli-'));

		await runAgentVmResourcesCommand(targetDir, 'init');

		await Promise.all(
			expectedResourceFiles.map(
				async (relativePath) =>
					await expect(fs.access(path.join(targetDir, relativePath))).resolves.toBeUndefined(),
			),
		);
		await expect(
			fs.access(path.join(targetDir, '.agent-vm', 'resources-post-hook.ts')),
		).rejects.toThrow(/ENOENT/u);

		const runSetupStat = await fs.stat(path.join(targetDir, '.agent-vm', 'run-setup.sh'));
		expect(runSetupStat.mode & 0o111).not.toBe(0);
		expect(await readResourceFile(targetDir, '.agent-vm/repo-resources.ts')).toContain(
			'describeRepoResources',
		);
		expect(await readResourceFile(targetDir, '.agent-vm/repo-resources.ts')).toContain(
			'finalizeRepoResourceSetup',
		);
		expect(await readResourceFile(targetDir, '.agent-vm/repo-resources.d.ts')).toContain(
			'Generated by agent-vm resources. Do not edit by hand.',
		);
		expect(await readResourceFile(targetDir, '.agent-vm/README.md')).toContain(
			'agent-vm resources update rewrites only repo-resources.d.ts',
		);

		await runAgentVmResourcesCommand(targetDir, 'validate');

		const userOwnedFiles = [
			'.agent-vm/repo-resources.ts',
			'.agent-vm/run-setup.sh',
			'.agent-vm/docker-compose.yml',
		] as const;
		await Promise.all(
			userOwnedFiles.map(async (relativePath) => {
				const commentPrefix = relativePath.endsWith('.ts') ? '//' : '#';
				await fs.appendFile(
					path.join(targetDir, relativePath),
					`\n${commentPrefix} smoke sentinel: ${relativePath}\n`,
				);
			}),
		);
		const userOwnedBeforeUpdate = await Promise.all(
			userOwnedFiles.map(
				async (relativePath) =>
					[relativePath, await readResourceFile(targetDir, relativePath)] as const,
			),
		);

		await fs.writeFile(
			path.join(targetDir, '.agent-vm', 'repo-resources.d.ts'),
			'// tampered generated declaration\n',
			'utf8',
		);
		await runAgentVmResourcesCommand(targetDir, 'update');

		await Promise.all(
			userOwnedBeforeUpdate.map(
				async ([relativePath, beforeUpdateContent]) =>
					await expect(readResourceFile(targetDir, relativePath)).resolves.toBe(
						beforeUpdateContent,
					),
			),
		);
		expect(await readResourceFile(targetDir, '.agent-vm/repo-resources.d.ts')).toContain(
			'Generated by agent-vm resources. Do not edit by hand.',
		);

		await runAgentVmResourcesCommand(targetDir, 'validate');
		await fs.writeFile(
			path.join(targetDir, '.agent-vm', 'resources-post-hook.ts'),
			'export {};\n',
			'utf8',
		);
		await expect(runAgentVmResourcesCommand(targetDir, 'validate')).rejects.toThrow(
			/resources-post-hook/u,
		);
	});
});
